In [ ]:
import numpy as np

In [ ]:
def get_rotate_matrix(motor_num, theta, a_len=1):
    if (motor_num == 0):
        R = [[ -np.sin(theta), 0, np.cos(theta), 0],
             [ np.cos(theta), 0, np.sin(theta), 0],
             [0, 1, 0, a_len],
             [0, 0, 0, 1]]
    elif (motor_num == 1):
        R = [[ np.cos(theta), 0, -np.sin(theta), a_len*np.cos(theta)],
             [ np.sin(theta), 0, np.cos(theta), a_len*np.sin(theta)],
             [ 0, -1, 0, 0],
             [0, 0, 0, 1]]
    elif (motor_num == 2):
        R = [[ np.cos(theta), 0, np.sin(theta), 0],
             [ np.sin(theta), 0, -np.cos(theta), 0],
             [0, 1, 0, a_len],
             [0, 0, 0, 1]]
    elif (motor_num == 3):
        R = [[ np.cos(theta), 0, -np.sin(theta), a_len*np.cos(theta)],
             [ np.sin(theta), 0, np.cos(theta), a_len*np.sin(theta)],
             [ 0, -1, 0, 0],
             [0, 0, 0, 1]]
    elif (motor_num == 4):
        R = [[ np.cos(theta), 0, np.sin(theta), 0],
             [ np.sin(theta), 0, -np.cos(theta), 0],
             [ 0, 1, 0, a_len],
             [0, 0, 0, 1]]
    elif (motor_num == 5):
        R = [[ np.cos(theta), -np.sin(theta), 0, a_len*np.cos(theta)],
             [ np.sin(theta), np.cos(theta), 0, a_len*np.sin(theta)],
             [ 0, 0, 1, 0],
             [0, 0, 0, 1]]
    return  R

def degrees_to_radians(degrees):
    return (degrees/180) * np.pi

def dot_product(a, b):
    zip_b = zip(*b)
    # uncomment next line if python 3 : 
    zip_b = list(zip_b)
    return [[sum(ele_a*ele_b for ele_a, ele_b in zip(row_a, col_b)) 
             for col_b in zip_b] for row_a in a]

In [ ]:
theta1 = degrees_to_radians(90)
theta2 = degrees_to_radians(0)
theta3 = degrees_to_radians(0)
theta4 = degrees_to_radians(0)
theta5 = degrees_to_radians(0)
theta6 = degrees_to_radians(90)


R0_1 = get_rotate_matrix(0, theta1)
R1_2 = get_rotate_matrix(1, theta2)
R2_3 = get_rotate_matrix(2, theta3)
R3_4 = get_rotate_matrix(3, theta4)
R4_5 = get_rotate_matrix(4, theta5)
R5_6 = get_rotate_matrix(5, theta6)

R0_2 = np.dot(R0_1, R1_2)
R2_4 = np.dot(R2_3, R3_4)
R4_6 = np.dot(R4_5, R5_6)

R0_4 = np.dot(R0_2, R2_4)
R0_6 = np.dot(R0_4, R4_6)

print('\nR0_1 = ')
print(np.matrix(R0_1))
print('\nR1_2 = ')
print(np.matrix(R1_2))
print('\nR2_3 = ')
print(np.matrix(R2_3))
print('\nR3_4 = ')
print(np.matrix(R3_4))
print('\nR4_5 = ')
print(np.matrix(R4_5))
print('\nR5_6 = ')
print(np.matrix(R5_6))
print('\nR0_6 = ')
print(np.matrix(R0_6))

In [ ]:
a1 = 1
a2 = 1
a3 = 1
a4 = 1

t1 = degrees_to_radians(90)
t2 = degrees_to_radians(0)

r0_1 = get_rotate_matrix(0, t1)
r1_2 = get_rotate_matrix(1, t2)

r0_2 = np.dot(r0_1, r1_2)

tr0_2 = dot_product(r0_1, r1_2)

print()
print(np.matrix(r0_2))
print()
print(np.matrix(tr0_2))

d0_1 = [[a2*np.cos(t1)],
        [a2*np.sin(t1)],
        [a1]]
d1_2 = [[a4*np.cos(t2 )],
        [a4*np.sin(t2)],
        [a3]]

#print(np.matrix(d0_1))
#print()

h0_1 = get_rotate_matrix(0, t1, 1)
h1_2 = get_rotate_matrix(1, t2, 1)
h0_2 = np.dot(h0_1, h1_2)

#np.matrix(h0_2)

In [ ]:
from mpl_toolkits.mplot3d import Axes3D
import matplotlib.pyplot as plt
x = [500, 500, 500.0, 500.0, 500.0, 500.0, 500.0]
y = [500, 500, 550.0, 550.0, 600.0, 600.0, 650.0]
z = [  0,  50,  50.0, 100.0, 100.0, 150.0, 150.0]
#x1 = [500, 500, 450.0, 450.0, 400.0, 400.0, 350.0]
#y1 = [500, 500, 499.99999781443057, 499.99999781443057, 499.99999562886114, 499.99999562886114, 499.99999344329177]
#z1 = [0, 50, 50.0, 100.0, 100.0, 150.0, 150.0]
#x2 = [500, 500, 500.0, 500.0, 500.0, 500.0, 500.0]
#y2 = [500, 500, 499.99999781443057, 449.99999781443057, 449.99999562886114, 399.99999562886114, 399.99999344329177]
#z2 = [0, 50, 100.0, 99.99999781443059, 149.99999781443057, 149.99999562886114, 199.99999562886114]
#x3 = [500, 500, 500.0, 500.0, 450.0, 450.0, 400.0]
#y3 = [500, 500, 550.0, 550.0, 549.9999978144306, 549.9999978144306, 549.9999956288611]
#z3 = [0, 50, 50.0, 100.0, 100.0, 150.0, 150.0]
#x4 = [500, 500, 500.0, 500.0, 500.0, 500.0, 500.0]
#y4 = [500, 500, 550.0, 550.0, 549.9999978144306, 499.99999781443057, 499.99999562886114]
#z4 = [0, 50, 50.0, 100.0, 150.0, 149.99999781443057, 199.99999781443057]
#x5 = [500, 500, 500.0, 500.0, 500.0, 500.0, 450.0]
#y5 = [500, 500, 550.0, 550.0, 600.0, 600.0, 599.9999978144306]
#z5 = [0, 50, 50.0, 100.0, 100.0, 150.0, 150.0]
#x6 = [500, 500, 500.0, 500.0, 500.0, 500.0, 500.0]
#y6 = [500, 500, 550.0, 550.0, 600.0, 600.0, 599.9999978144306]
#z6 = [0, 50, 50.0, 100.0, 100.0, 150.0, 200.0]
x7 = [500, 500.0, 500.0, 500.0, 500.0, 500.0, 499.99999781443057]
y7 = [500, 500.0, 500.0, 500.0, 500.0, 500.0, 499.99999781443057]
z7 = [0, 50, 50.0, 100.0000000000001, 100.0000000000001, 150.00000000000028, 100.00000000000009]
fig = plt.figure()
ax = fig.add_subplot(111, projection='3d')
ax.plot(x, y, z, linewidth=4)
ax.plot(x1, y1, z1)
ax.plot(x2, y2, z2)
ax.plot(x3, y3, z3)
ax.plot(x4, y4, z4)
ax.plot(x5, y5, z5)
ax.plot(x6, y6, z6)
ax.plot(x7, y7, z7)
plt.xlabel('X Axis')
plt.ylabel('Y Axis')
plt.show()

In [19]:
import numpy as np
from jacobian import Jacobian

PI = 3.14159265359

class JacobianInverseKinematics:
    def __init__(self):
        self.joint_count = 7
        self.theta_list = np.zeros(self.joint_count)
        self.tms = list()
        self.p_lists = list()

    def get_transformation_matrix(self, motor_num, theta):
        link_lengths = [50, 100, 100, 50]
        ninety = (90/180.0)*np.pi
        one_80 = np.pi
        PTs= [['(θ)',  '(90)', '(0)',    'a1'],
              ['(θ)', '(-90)', '(0)',   '(0)'],
              ['(θ)',  '(90)', '(0)', 'a2+a3'],
              ['(θ)', '(-90)', '(0)',   '(0)'],
              ['(θ)',  '(90)', '(0)', 'a4+a5'],
              ['(θ)', '(-90)', '(0)',   '(0)'],
              ['(θ)',   '(0)', '(0)',    'a6']]

        PT = [[ theta, ninety, 0, link_lengths[0]],
              [ theta,-ninety, 0,             0],
              [ theta, ninety, 0, link_lengths[1]],
              [ theta,-ninety, 0,             0],
              [ theta, ninety, 0, link_lengths[2]],
              [ theta,-ninety, 0,             0],
              [ theta,      0, 0, link_lengths[3]]]

        '''
        PT = [[theta-ninety,      0, 0, link_lengths[0]],
              [           0,  theta, 0,               0],
              [       theta,      0, 0, link_lengths[1]],
              [           0,  theta, 0,               0],
              [       theta, ninety, 0, link_lengths[2]],
              [           0,      0, 0, link_lengths[3]]]
        PT = [[ theta+ninety,       0,               0, link_lengths[0]],
              [            0,  -theta,               0,               0],
              [ theta-ninety, -ninety,               0, link_lengths[1]],
              [-theta+one_80, -ninety,               0,               0],
              [        theta, -ninety,               0, link_lengths[2]],
              [ theta-ninety,       0, link_lengths[3],               0]]
        PT1 =[[ theta+one_80, -ninety,               0, link_lengths[0]],
              [ theta+one_80, -ninety,               0,               0],
              [        theta, -ninety,               0, link_lengths[1]],
              [-theta+one_80, -ninety,               0,               0],
              [        theta, -ninety,               0, link_lengths[2]],
              [ theta-ninety,       0, link_lengths[3],               0]]
        
        TMs= [['cos{}'.format(PTs[motor_num][0]), '-sin{}cos{}'.format(PTs[motor_num][0], PTs[motor_num][1]), 'sin{}sin{}'.format(PTs[motor_num][0], PTs[motor_num][1]), '{}cos{}'.format(PTs[motor_num][2], PTs[motor_num][0])],
              ['sin{}'.format(PTs[motor_num][0]), 'cos{}cos{}'.format(PTs[motor_num][0], PTs[motor_num][1]), '-cos{}sin{}'.format(PTs[motor_num][0], PTs[motor_num][1]), '{}sin{}'.format(PTs[motor_num][2], PTs[motor_num][0])],
              ['0', 'sin{}'.format(PTs[motor_num][1]), 'cos{}'.format(PTs[motor_num][1]), '{}'.format(PTs[motor_num][3])],
              ['0','0','0','1']]
        
        self.tms.append(TMs)
        '''
        return [[np.cos(PT[motor_num][0]), -np.sin(PT[motor_num][0])*np.cos(PT[motor_num][1]), np.sin(PT[motor_num][0])*np.sin(PT[motor_num][1]), PT[motor_num][2]*np.cos(PT[motor_num][0])],
                [np.sin(PT[motor_num][0]), np.cos(PT[motor_num][0])*np.cos(PT[motor_num][1]), -np.cos(PT[motor_num][0])*np.sin(PT[motor_num][1]), PT[motor_num][2]*np.sin(PT[motor_num][0])],
                [0, np.sin(PT[motor_num][1]), np.cos(PT[motor_num][1]), PT[motor_num][3]],
                [0,0,0,1]]
    
    def forward(self, theta_list):
        p_list = list()
        for i, angle in enumerate(theta_list):
            tm = self.get_transformation_matrix(i, angle)
            if(i == 0): 
                buff = tm
            else: 
                buff = np.dot(buff, tm)
            p_list.append(buff)
        self.p_lists = p_list
        return np.array(p_list)
    
    def inverse(self, goal, q):
        gamma = 0.01
        fk = self.forward(q)
        end = fk[-1,:3,3].tolist()
        end.extend(fk[-1,:3,2].tolist())
        d = np.subtract(goal, end)
        print(np.round(d,decimals=4))
        J = Jacobian(q, [50,50,50,50,50,50])
        step = np.dot(np.linalg.pinv(J), d.reshape(6,))
        q = q + (step * gamma)
        return q
    
    def normalize(self, x):
        return x/np.linalg.norm(x)
    
    def radians(self, degrees):
        return (degrees/180) * np.pi
    
    def dots(self, a, b):
        c = [['']*4]*4
        for i in range(4):
            for j in range(4):
                buff = ''
                for k in range(4):
                    buff = a[i][k]+b[k][j]+'+'+buff
                c[i][j] = buff
        return c

In [21]:
from mpl_toolkits.mplot3d import Axes3D
import matplotlib.pyplot as plt
%matplotlib inline
jik = JacobianInverseKinematics()
q = np.array([0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1])
q1 = np.array([jik.radians(-45),jik.radians(-45),jik.radians(0),jik.radians(90),jik.radians(0),jik.radians(45), 0.1])
q2 = np.array([jik.radians(-45),jik.radians(45),jik.radians(0),jik.radians(-90),0,jik.radians(-45),0.1])
goal = np.array([35., -35., 191., 0.7, -0.7, 0.000001])
j = 0
threshold = 1.01
err = 100
lowest = 10000
#'''
#while(err > threshold):
#for i in range(1000):
while(err > threshold):
    j += 1
    q = jik.inverse(goal, q)
    coords = jik.forward(q)
    pos = coords[-1,:3,3].tolist()
    pos.extend(coords[-1,:3,2].tolist())
    err = np.sqrt(np.sum(np.power(np.subtract(goal, pos), 2)))
    if (lowest > err):
        lowest = err
    print(err)
    if (err < threshold):
        break
#
print ('Epocs = {}'.format(j))
print ('Error = {}'.format(err))
print ('Lowst = {}'.format(lowest))
x = [0]
y = [0]
z = [0]
for i in range(7):
    x.append(coords[i,0,3])
    y.append(coords[i,1,3])
    z.append(coords[i,2,3])
x = [int(x_) for x_ in x]
y = [int(y_) for y_ in y]
z = [int(z_) for z_ in z]
'''
for i, block in enumerate(jik.tms):
    for row in block:
        row = str(row)
        row = row.replace('cos', 'sp.cos')
        row = row.replace('sin', 'sp.sin')
        row = row.replace('90', 'r90')
        row = row.replace('180', 'r180')
        row = row.replace('sp.cos(r90)', '(0)')
        row = row.replace('sp.cos(-r90)', '(0)')
        row = row.replace('sp.sin(r90)', '(1)')
        row = row.replace('sp.sin(-r90)', '(-1)')
        row = row.replace('sp.sin(0)', '0')
        row = row.replace('sp.cos(0)', '1')
        row = row.replace('a', 'l')
        row = row.replace("'", '')
        row = row.replace('θ', 'q[{}]'.format(i))
        print(row)
    print('')
'''
fig = plt.figure()
ax = fig.add_subplot(111, projection='3d')
ax.plot(x, y, z, linewidth=4)
plt.xlabel('X Axis')
plt.ylabel('Y Axis')
print(x)
print(y)
print(z)
print('')
for row in jik.p_lists[-1].tolist():
    print(row)
print('')


coords = jik.forward(q2)
x = [0]
y = [0]
z = [0]
for i in range(7):
    x.append(coords[i,0,3])
    y.append(coords[i,1,3])
    z.append(coords[i,2,3])
    
x = [0.0 if(x_>-0.1 and x_<0.1) else x_ for x_ in x]
y = [0.0 if(y_>-0.1 and y_<0.1) else y_ for y_ in y]
z = [0.0 if(z_>-0.1 and z_<0.1) else z_ for z_ in z]
fig = plt.figure()
ax2 = fig.add_subplot(111, projection='3d')
ax2.plot(x, y, z, linewidth=4)
plt.xlabel('X Axis')
plt.ylabel('Y Axis')
plt.show()

print(x)
print(y)
print(z)
print('')
for row in jik.p_lists[-1].tolist():
    print(row)
print('')
print(q)


(6,)
(6,)
[  78.9836  -28.0927 -104.2937    0.9886   -0.6412   -0.9556]
130.7320808205823
(6,)
(6,)
[  77.8276  -24.9351 -102.0279    0.9971   -0.6314   -0.9524]
133.93906306704534
(6,)
(6,)
[ 83.3084 -31.9039 -99.8956   1.0324  -0.6585  -0.9422]
131.1177449809824
(6,)
(6,)
[ 80.617  -29.3831 -99.1314   1.032   -0.6425  -0.9415]
129.46515391376911
(6,)
(6,)
[ 79.4332 -28.5988 -98.1394   1.0368  -0.6333  -0.9392]
127.96421477266385
(6,)
(6,)
[ 78.4231 -28.0273 -97.143    1.0424  -0.6252  -0.9366]
126.53868532180908
(6,)
(6,)
[ 77.4941 -27.5487 -96.1531   1.0483  -0.6177  -0.9338]
125.16306643597522
(6,)
(6,)
[ 76.616  -27.124  -95.1721   1.0543  -0.6104  -0.9308]
123.82476118555054
(6,)
(6,)
[ 75.7738 -26.7348 -94.2009   1.0605  -0.6034  -0.9278]
122.51645725937989
(6,)
(6,)
[ 74.959  -26.371  -93.2398   1.0667  -0.5965  -0.9246]
121.23349920118831
(6,)
(6,)
[ 74.166  -26.0265 -92.2889   1.073   -0.5897  -0.9213]
119.97272837290042
(6,)
(6,)
[ 73.3911 -25.6973 -91.3482   1.0793  -0.583 

48.374823581472114
(6,)
(6,)
[ 29.7192 -10.3442 -36.7088   1.4947  -0.1741  -0.303 ]
47.89104775373029
(6,)
(6,)
[ 29.421  -10.2451 -36.3406   1.4968  -0.172   -0.2938]
47.412124209762936
(6,)
(6,)
[ 29.1258 -10.147  -35.9761   1.4989  -0.17    -0.2845]
46.93800467567461
(6,)
(6,)
[ 28.8335 -10.0499 -35.6153   1.5008  -0.1681  -0.2752]
46.468641379688684
(6,)
(6,)
[ 28.5441  -9.9537 -35.2581   1.5027  -0.1662  -0.2659]
46.00398704649063
(6,)
(6,)
[ 28.2576  -9.8584 -34.9045   1.5046  -0.1644  -0.2565]
45.54399489165273
(6,)
(6,)
[ 27.974   -9.7641 -34.5545   1.5064  -0.1627  -0.2471]
45.08861861613926
(6,)
(6,)
[ 27.6932  -9.6707 -34.2081   1.5081  -0.161   -0.2377]
44.637812400890525
(6,)
(6,)
[ 27.4151  -9.5782 -33.8651   1.5097  -0.1594  -0.2283]
44.19153090148473
(6,)
(6,)
[ 27.1399  -9.4867 -33.5256   1.5113  -0.1579  -0.2188]
43.749729242876874
(6,)
(6,)
[ 26.8674  -9.396  -33.1895   1.5128  -0.1564  -0.2093]
43.31236301421311
(6,)
(6,)
[ 26.5976  -9.3062 -32.8568   1.5143  -0.15

16.038522873633422
(6,)
(6,)
[  9.7793  -3.7417 -12.0517   1.3262  -0.3433   0.6933]
15.88549042174238
(6,)
(6,)
[  9.6857  -3.714  -11.9326   1.3213  -0.3481   0.7001]
15.734210177494782
(6,)
(6,)
[  9.5932  -3.6869 -11.8147   1.3163  -0.353    0.7069]
15.584674667555404
(6,)
(6,)
[  9.5018  -3.6603 -11.698    1.3114  -0.3579   0.7136]
15.436877632834609
(6,)
(6,)
[  9.4115  -3.6344 -11.5825   1.3063  -0.3629   0.7202]
15.290814280040184
(6,)
(6,)
[  9.3223  -3.6092 -11.4682   1.3012  -0.368    0.7268]
15.146481611965186
(6,)
(6,)
[  9.2343  -3.5847 -11.3551   1.2961  -0.373    0.7333]
15.003878865674317
(6,)
(6,)
[  9.1473  -3.5608 -11.243    1.291   -0.3782   0.7397]
14.863008100868106
(6,)
(6,)
[  9.0615  -3.5378 -11.1322   1.2857  -0.3833   0.7461]
14.723875001049992
(6,)
(6,)
[  8.9769  -3.5155 -11.0224   1.2805  -0.3885   0.7523]
14.586489982570152
(6,)
(6,)
[  8.8933  -3.4942 -10.9137   1.2752  -0.3938   0.7585]
14.450869759962824
(6,)
(6,)
[  8.811   -3.4738 -10.806    1.2699 

15.734260374682979
(6,)
(6,)
[14.008  -6.1764  3.2423  0.379  -1.5226  0.4694]
15.578769627108166
(6,)
(6,)
[13.8687 -6.1133  3.2096  0.3756 -1.5258  0.4613]
15.4248759030676
(6,)
(6,)
[13.7308 -6.0509  3.1773  0.3724 -1.529   0.4533]
15.272562588663071
(6,)
(6,)
[13.5943 -5.9892  3.1453  0.3692 -1.5321  0.4452]
15.121813282955024
(6,)
(6,)
[13.4592 -5.9281  3.1136  0.3661 -1.5352  0.437 ]
14.97261179270827
(6,)
(6,)
[13.3254 -5.8677  3.0823  0.363  -1.5382  0.4288]
14.824942127456525
(6,)
(6,)
[13.193  -5.808   3.0513  0.36   -1.5411  0.4206]
14.678788494851858
(6,)
(6,)
[13.0618 -5.7489  3.0206  0.357  -1.544   0.4123]
14.534135296271318
(6,)
(6,)
[12.932  -5.6904  2.9902  0.3541 -1.5469  0.404 ]
14.390967122655582
(6,)
(6,)
[12.8035 -5.6326  2.9602  0.3513 -1.5496  0.3956]
14.249268750559366
(6,)
(6,)
[12.6763 -5.5753  2.9304  0.3485 -1.5524  0.3872]
14.109025138394228
(6,)
(6,)
[12.5504 -5.5187  2.901   0.3458 -1.555   0.3788]
13.970221422848287
(6,)
(6,)
[12.4257 -5.4627  2.8719  

3.2243631278840517
(6,)
(6,)
[ 2.493  -1.0361  0.6585  0.7113 -1.1847 -0.8746]
3.2007894334381843
(6,)
(6,)
[ 2.4683 -1.0253  0.6536  0.7175 -1.1785 -0.8779]
3.1774783389484367
(6,)
(6,)
[ 2.4438 -1.0145  0.6487  0.7236 -1.1723 -0.8811]
3.154426643007076
(6,)
(6,)
[ 2.4195 -1.0039  0.6439  0.7297 -1.1661 -0.8842]
3.131631169409471
(6,)
(6,)
[ 2.3954 -0.9933  0.6392  0.7359 -1.1599 -0.8872]
3.109088767262936
(6,)
(6,)
[ 2.3715 -0.9828  0.6344  0.7421 -1.1537 -0.8902]
3.086796311129797
(6,)
(6,)
[ 2.3478 -0.9724  0.6298  0.7483 -1.1474 -0.893 ]
3.0647507012079096
(6,)
(6,)
[ 2.3243 -0.9621  0.6251  0.7545 -1.1411 -0.8958]
3.042948863552971
(6,)
(6,)
[ 2.301  -0.9519  0.6205  0.7608 -1.1348 -0.8985]
3.0213877503473228
(6,)
(6,)
[ 2.2779 -0.9418  0.616   0.767  -1.1285 -0.901 ]
3.000064340220133
(6,)
(6,)
[ 2.2549 -0.9318  0.6114  0.7733 -1.1222 -0.9035]
2.978975638625173
(6,)
(6,)
[ 2.2322 -0.9218  0.607   0.7796 -1.1158 -0.906 ]
2.9581186782823083
(6,)
(6,)
[ 2.2096 -0.9119  0.6025  0.78

[ 0.2567 -0.0738  0.2056  1.5972 -0.2807  0.1383]
1.6616615629033296
(6,)
(6,)
[ 0.2551 -0.0742  0.2038  1.5962 -0.2816  0.1475]
1.661201730870115
(6,)
(6,)
[ 0.2535 -0.0747  0.202   1.5951 -0.2827  0.1567]
1.660753886139137
(6,)
(6,)
[ 0.252  -0.0751  0.2002  1.594  -0.2838  0.1659]
1.6603179400625008
(6,)
(6,)
[ 0.2505 -0.0756  0.1983  1.5928 -0.285   0.1751]
1.659893810951803
(6,)
(6,)
[ 0.2491 -0.0761  0.1964  1.5915 -0.2862  0.1842]
1.6594814241160252
(6,)
(6,)
[ 0.2478 -0.0766  0.1946  1.5902 -0.2875  0.1934]
1.6590807119003714
(6,)
(6,)
[ 0.2465 -0.0771  0.1927  1.5888 -0.2889  0.2025]
1.6586916137252952
(6,)
(6,)
[ 0.2452 -0.0777  0.1908  1.5873 -0.2903  0.2116]
1.6583140761246926
(6,)
(6,)
[ 0.2441 -0.0782  0.1889  1.5858 -0.2918  0.2207]
1.6579480527821806
(6,)
(6,)
[ 0.2429 -0.0788  0.187   1.5842 -0.2933  0.2298]
1.6575935045641546
(6,)
(6,)
[ 0.2419 -0.0794  0.1851  1.5826 -0.295   0.2388]
1.657250399548188
(6,)
(6,)
[ 0.2409 -0.0801  0.1832  1.5808 -0.2967  0.2478]
1.6569

1.656508373247012
(6,)
(6,)
[ 0.2232 -0.2116 -0.1121  0.5559 -1.3133  0.7766]
1.6561041571661446
(6,)
(6,)
[ 0.2219 -0.2104 -0.1113  0.5505 -1.3187  0.7713]
1.6557053032509232
(6,)
(6,)
[ 0.2205 -0.2091 -0.1104  0.5451 -1.3241  0.7659]
1.655311783081559
(6,)
(6,)
[ 0.2192 -0.2079 -0.1095  0.5397 -1.3294  0.7604]
1.6549235636872455
(6,)
(6,)
[ 0.2179 -0.2067 -0.1087  0.5344 -1.3347  0.7548]
1.654540608073119
(6,)
(6,)
[ 0.2167 -0.2055 -0.1078  0.5292 -1.3399  0.7492]
1.6541628756980464
(6,)
(6,)
[ 0.2154 -0.2043 -0.1069  0.5239 -1.3451  0.7435]
1.6537903229078823
(6,)
(6,)
[ 0.2142 -0.203  -0.1061  0.5187 -1.3503  0.7377]
1.6534229033285697
(6,)
(6,)
[ 0.213  -0.2018 -0.1052  0.5136 -1.3554  0.7319]
1.6530605682227015
(6,)
(6,)
[ 0.2118 -0.2006 -0.1043  0.5085 -1.3605  0.726 ]
1.6527032668130703
(6,)
(6,)
[ 0.2106 -0.1994 -0.1034  0.5034 -1.3656  0.72  ]
1.6523509465762338
(6,)
(6,)
[ 0.2095 -0.1982 -0.1026  0.4984 -1.3706  0.7139]
1.6520035535088657
(6,)
(6,)
[ 0.2084 -0.197  -0.1017  

[ 0.1534 -0.0456  0.0611  0.4794 -1.3875 -0.6919]
1.631884575964906
(6,)
(6,)
[ 0.1531 -0.0449  0.0621  0.4843 -1.3826 -0.6982]
1.631874939232521
(6,)
(6,)
[ 0.1529 -0.0443  0.0632  0.4892 -1.3777 -0.7044]
1.6318650207745033
(6,)
(6,)
[ 0.1527 -0.0436  0.0642  0.4941 -1.3728 -0.7106]
1.631854770653834
(6,)
(6,)
[ 0.1524 -0.0429  0.0652  0.4991 -1.3678 -0.7167]
1.6318441381411442
(6,)
(6,)
[ 0.1522 -0.0423  0.0662  0.5041 -1.3627 -0.7228]
1.6318330717352618
(6,)
(6,)
[ 0.1519 -0.0416  0.0672  0.5092 -1.3576 -0.7288]
1.631821519186288
(6,)
(6,)
[ 0.1516 -0.0409  0.0682  0.5143 -1.3525 -0.7347]
1.631809427521313
(6,)
(6,)
[ 0.1513 -0.0403  0.0692  0.5194 -1.3473 -0.7405]
1.6317967430729583
(6,)
(6,)
[ 0.151  -0.0396  0.0702  0.5246 -1.3421 -0.7463]
1.6317834115107133
(6,)
(6,)
[ 0.1507 -0.0389  0.0712  0.5299 -1.3369 -0.7519]
1.6317693778752527
(6,)
(6,)
[ 0.1503 -0.0383  0.0722  0.5351 -1.3316 -0.7576]
1.631754586615764
(6,)
(6,)
[ 0.15   -0.0376  0.0731  0.5404 -1.3263 -0.7631]
1.631738

1.6324429413511337
(6,)
(6,)
[-0.0675  0.1384  0.1733  1.5089 -0.3419 -0.4662]
1.6324102525730553
(6,)
(6,)
[-0.0675  0.1378  0.1737  1.5122 -0.3386 -0.458 ]
1.6323712651706768
(6,)
(6,)
[-0.0675  0.1372  0.1742  1.5153 -0.3353 -0.4497]
1.632326077169465
(6,)
(6,)
[-0.0674  0.1365  0.1746  1.5184 -0.3322 -0.4414]
1.632274790365561
(6,)
(6,)
[-0.0674  0.1359  0.1749  1.5215 -0.329  -0.4331]
1.6322175099669833
(6,)
(6,)
[-0.0673  0.1352  0.1752  1.5245 -0.326  -0.4247]
1.6321543442554365
(6,)
(6,)
[-0.0672  0.1344  0.1755  1.5274 -0.323  -0.4162]
1.6320854042677053
(6,)
(6,)
[-0.0672  0.1336  0.1758  1.5303 -0.32   -0.4078]
1.6320108034960585
(6,)
(6,)
[-0.0671  0.1328  0.176   1.5331 -0.3172 -0.3993]
1.6319306576067187
(6,)
(6,)
[-0.067   0.132   0.1762  1.5358 -0.3143 -0.3907]
1.6318450841756795
(6,)
(6,)
[-0.0669  0.1311  0.1764  1.5385 -0.3116 -0.3821]
1.6317542024410696
(6,)
(6,)
[-0.0667  0.1303  0.1765  1.5412 -0.3089 -0.3735]
1.6316581330713726
(6,)
(6,)
[-0.0666  0.1294  0.1766 

1.634799765583364
(6,)
(6,)
[ 0.2246 -0.1243 -0.0794  1.0106 -0.8326  0.9413]
1.6355331445751522
(6,)
(6,)
[ 0.2279 -0.1257 -0.082   1.004  -0.8392  0.9424]
1.636337916775966
(6,)
(6,)
[ 0.2316 -0.1273 -0.0846  0.9975 -0.8458  0.9435]
1.6372200673680506
(6,)
(6,)
[ 0.2354 -0.1291 -0.0874  0.991  -0.8524  0.9445]
1.638185410909844
(6,)
(6,)
[ 0.2396 -0.1311 -0.0904  0.9844 -0.8591  0.9454]
1.6392392282293673
(6,)
(6,)
[ 0.244  -0.1332 -0.0935  0.9779 -0.8657  0.9462]
1.6403857726575841
(6,)
(6,)
[ 0.2488 -0.1355 -0.0967  0.9714 -0.8724  0.9469]
1.6416276461582064
(6,)
(6,)
[ 0.2538 -0.1379 -0.1001  0.9648 -0.8791  0.9475]
1.6429650858162868
(6,)
(6,)
[ 0.2591 -0.1404 -0.1036  0.9583 -0.8858  0.948 ]
1.6443952709810599
(6,)
(6,)
[ 0.2648 -0.143  -0.1071  0.9518 -0.8924  0.9484]
1.6459118613852226
(6,)
(6,)
[ 0.2706 -0.1457 -0.1108  0.9453 -0.8991  0.9488]
1.6475050829711981
(6,)
(6,)
[ 0.2767 -0.1483 -0.1145  0.9389 -0.9058  0.949 ]
1.6491627235459594
(6,)
(6,)
[ 0.283  -0.1508 -0.1182  

1.6266802737851411
(6,)
(6,)
[ 0.1197 -0.179  -0.0811  0.3463 -1.4917  0.4981]
1.6264080207573646
(6,)
(6,)
[ 0.1194 -0.1772 -0.08    0.3428 -1.4951  0.4901]
1.6261405243572922
(6,)
(6,)
[ 0.1191 -0.1755 -0.079   0.3394 -1.4985  0.482 ]
1.6258777161375526
(6,)
(6,)
[ 0.1187 -0.1738 -0.0779  0.3361 -1.5019  0.4739]
1.6256195287321515
(6,)
(6,)
[ 0.1184 -0.1721 -0.0769  0.3328 -1.5052  0.4657]
1.6253658958459456
(6,)
(6,)
[ 0.1181 -0.1704 -0.0759  0.3295 -1.5084  0.4575]
1.6251167522437044
(6,)
(6,)
[ 0.1178 -0.1687 -0.0748  0.3264 -1.5115  0.4492]
1.6248720337389235
(6,)
(6,)
[ 0.1175 -0.1671 -0.0738  0.3232 -1.5147  0.4409]
1.6246316771823266
(6,)
(6,)
[ 0.1172 -0.1654 -0.0728  0.3202 -1.5177  0.4325]
1.6243956204501924
(6,)
(6,)
[ 0.1169 -0.1638 -0.0718  0.3172 -1.5207  0.4241]
1.6241638024324592
(6,)
(6,)
[ 0.1166 -0.1621 -0.0708  0.3142 -1.5236  0.4157]
1.6239361630207425
(6,)
(6,)
[ 0.1164 -0.1605 -0.0697  0.3113 -1.5265  0.4072]
1.6237126430962012
(6,)
(6,)
[ 0.1161 -0.1589 -0.068

1.6160642680057833
(6,)
(6,)
[ 0.1118 -0.0066  0.1008  0.6986 -1.1364 -0.8997]
1.61603725589804
(6,)
(6,)
[ 0.1109 -0.006   0.1016  0.7048 -1.1301 -0.9028]
1.6160077767971073
(6,)
(6,)
[ 0.1101 -0.0054  0.1025  0.7111 -1.1237 -0.9057]
1.615975786675786
(6,)
(6,)
[ 0.1092 -0.0048  0.1033  0.7175 -1.1174 -0.9086]
1.615941244195375
(6,)
(6,)
[ 0.1083 -0.0042  0.1041  0.7238 -1.111  -0.9113]
1.61590411092321
(6,)
(6,)
[ 0.1073 -0.0035  0.1049  0.7302 -1.1046 -0.914 ]
1.6158643515616287
(6,)
(6,)
[ 0.1063 -0.0029  0.1056  0.7365 -1.0981 -0.9166]
1.6158219341891595
(6,)
(6,)
[ 0.1052 -0.0023  0.1064  0.7429 -1.0917 -0.9191]
1.615776830515008
(6,)
(6,)
[ 0.1041 -0.0016  0.1071  0.7494 -1.0852 -0.9215]
1.6157290161477083
(6,)
(6,)
[ 1.0300e-01 -1.0000e-03  1.0790e-01  7.5580e-01 -1.0787e+00 -9.2380e-01]
1.6156784708791545
(6,)
(6,)
[ 1.0190e-01 -3.0000e-04  1.0860e-01  7.6220e-01 -1.0722e+00 -9.2600e-01]
1.6156251789852212
(6,)
(6,)
[ 1.0060e-01  4.0000e-04  1.0930e-01  7.6870e-01 -1.0657e+00 

1.622571949787589
(6,)
(6,)
[-0.0797  0.1651  0.1686  1.3759 -0.446  -0.6919]
1.6227886303247019
(6,)
(6,)
[-0.0797  0.1659  0.1703  1.3807 -0.4411 -0.6853]
1.6229956621162536
(6,)
(6,)
[-0.0798  0.1666  0.172   1.3855 -0.4363 -0.6787]
1.623192833364423
(6,)
(6,)
[-0.0799  0.1672  0.1737  1.3902 -0.4314 -0.672 ]
1.6233799661688513
(6,)
(6,)
[-0.0799  0.1678  0.1753  1.3948 -0.4267 -0.6652]
1.6235569143594044
(6,)
(6,)
[-0.08    0.1683  0.1768  1.3995 -0.4219 -0.6583]
1.6237235613960332
(6,)
(6,)
[-0.0801  0.1687  0.1783  1.404  -0.4172 -0.6514]
1.6238798183456562
(6,)
(6,)
[-0.0801  0.1691  0.1797  1.4086 -0.4126 -0.6445]
1.624025621942626
(6,)
(6,)
[-0.0802  0.1694  0.1811  1.4131 -0.408  -0.6374]
1.6241609327370523
(6,)
(6,)
[-0.0803  0.1696  0.1825  1.4175 -0.4035 -0.6303]
1.624285733333232
(6,)
(6,)
[-0.0803  0.1698  0.1838  1.4219 -0.399  -0.6232]
1.6244000267187617
(6,)
(6,)
[-0.0804  0.1699  0.185   1.4262 -0.3946 -0.616 ]
1.6245038346841076
(6,)
(6,)
[-0.0804  0.1699  0.1862  1

1.6102072369022389
(6,)
(6,)
[ 0.1548 -0.104   0.0091  1.3181 -0.4946  0.7588]
1.6105354122622644
(6,)
(6,)
[ 0.1573 -0.1058  0.0069  1.3128 -0.4999  0.7645]
1.6108585650462313
(6,)
(6,)
[ 0.1598 -0.1075  0.0048  1.3074 -0.5053  0.7702]
1.6111756626225393
(6,)
(6,)
[ 0.1621 -0.1092  0.0026  1.302  -0.5107  0.7758]
1.6114857722463494
(6,)
(6,)
[ 1.6430e-01 -1.1080e-01  5.0000e-04  1.2965e+00 -5.1610e-01  7.8130e-01]
1.6117880720488014
(6,)
(6,)
[ 0.1664 -0.1123 -0.0016  1.291  -0.5215  0.7867]
1.612081859836537
(6,)
(6,)
[ 0.1685 -0.1137 -0.0036  1.2854 -0.527   0.792 ]
1.6123665595979788
(6,)
(6,)
[ 0.1704 -0.1151 -0.0056  1.2799 -0.5326  0.7973]
1.6126417257017789
(6,)
(6,)
[ 0.1723 -0.1163 -0.0076  1.2743 -0.5381  0.8025]
1.6129070448562863
(6,)
(6,)
[ 0.1741 -0.1175 -0.0095  1.2686 -0.5437  0.8076]
1.6131623359722238
(6,)
(6,)
[ 0.1758 -0.1186 -0.0114  1.2629 -0.5494  0.8127]
1.613407548131776
(6,)
(6,)
[ 0.1774 -0.1196 -0.0133  1.2572 -0.555   0.8176]
1.613642756913294
(6,)
(6,)
[ 

1.6183561996567009
(6,)
(6,)
[ 0.138  -0.1373 -0.0817  0.3772 -1.4475  0.5806]
1.6176888524940067
(6,)
(6,)
[ 0.1357 -0.1331 -0.0789  0.3732 -1.4515  0.5731]
1.6170350925933255
(6,)
(6,)
[ 0.1333 -0.1289 -0.0761  0.3692 -1.4555  0.5655]
1.6163961183974656
(6,)
(6,)
[ 0.1309 -0.1248 -0.0732  0.3653 -1.4594  0.5579]
1.6157732946696592
(6,)
(6,)
[ 0.1283 -0.1207 -0.0703  0.3615 -1.4633  0.5502]
1.6151681516589675
(6,)
(6,)
[ 0.1257 -0.1168 -0.0674  0.3577 -1.4672  0.5425]
1.614582375546867
(6,)
(6,)
[ 0.123  -0.1129 -0.0644  0.3539 -1.4709  0.5347]
1.614017787553599
(6,)
(6,)
[ 0.1203 -0.1093 -0.0613  0.3503 -1.4747  0.5269]
1.613476309257641
(6,)
(6,)
[ 0.1174 -0.1057 -0.0582  0.3466 -1.4783  0.519 ]
1.6129599123673752
(6,)
(6,)
[ 0.1145 -0.1024 -0.0552  0.3431 -1.4819  0.5111]
1.6124705525214877
(6,)
(6,)
[ 0.1115 -0.0993 -0.0521  0.3396 -1.4855  0.5031]
1.6120100887196664
(6,)
(6,)
[ 0.1084 -0.0965 -0.049   0.3361 -1.489   0.4951]
1.6115801925400526
(6,)
(6,)
[ 0.1053 -0.094  -0.0459  

1.6047247616859517
(6,)
(6,)
[-6.4000e-03 -3.0000e-04  7.6400e-02  4.8920e-01 -1.3317e+00 -7.4600e-01]
1.60473985523334
(6,)
(6,)
[-6.6000e-03  1.1000e-03  7.7200e-02  4.9440e-01 -1.3264e+00 -7.5190e-01]
1.6047566395347477
(6,)
(6,)
[-0.0069  0.0024  0.0781  0.4997 -1.3211 -0.7577]
1.6047751029119504
(6,)
(6,)
[-0.0071  0.0037  0.079   0.505  -1.3157 -0.7634]
1.6047952324901518
(6,)
(6,)
[-0.0073  0.0051  0.0799  0.5103 -1.3104 -0.7691]
1.604817014196231
(6,)
(6,)
[-0.0075  0.0064  0.0808  0.5156 -1.3049 -0.7746]
1.604840432758295
(6,)
(6,)
[-0.0078  0.0077  0.0817  0.521  -1.2995 -0.7801]
1.6048654717065556
(6,)
(6,)
[-0.008   0.009   0.0826  0.5265 -1.294  -0.7856]
1.604892113375695
(6,)
(6,)
[-0.0082  0.0103  0.0835  0.532  -1.2884 -0.7909]
1.604920338908809
(6,)
(6,)
[-0.0085  0.0116  0.0844  0.5375 -1.2828 -0.7962]
1.6049501282630094
(6,)
(6,)
[-0.0087  0.0129  0.0853  0.543  -1.2772 -0.8013]
1.604981460216792
(6,)
(6,)
[-0.009   0.0142  0.0862  0.5486 -1.2716 -0.8065]
1.605014312

1.6088010610794445
(6,)
(6,)
[-0.0999 -0.0129  0.1535  1.5582 -0.2521 -0.2507]
1.6087415546134718
(6,)
(6,)
[-0.1    -0.0137  0.1528  1.5599 -0.2504 -0.2416]
1.6086813707886518
(6,)
(6,)
[-0.1002 -0.0145  0.1521  1.5616 -0.2487 -0.2324]
1.6086205269344955
(6,)
(6,)
[-0.1004 -0.0153  0.1514  1.5632 -0.2471 -0.2232]
1.6085590405419514
(6,)
(6,)
[-0.1005 -0.0161  0.1507  1.5647 -0.2456 -0.214 ]
1.6084969292518765
(6,)
(6,)
[-0.1006 -0.0169  0.15    1.5662 -0.2441 -0.2047]
1.6084342108437066
(6,)
(6,)
[-0.1008 -0.0177  0.1493  1.5675 -0.2427 -0.1955]
1.6083709032241793
(6,)
(6,)
[-0.1009 -0.0185  0.1485  1.5689 -0.2413 -0.1862]
1.6083070244162876
(6,)
(6,)
[-0.101  -0.0193  0.1478  1.5701 -0.24   -0.1769]
1.6082425925483375
(6,)
(6,)
[-0.1011 -0.0201  0.147   1.5713 -0.2388 -0.1676]
1.608177625843167
(6,)
(6,)
[-0.1012 -0.0209  0.1462  1.5725 -0.2377 -0.1583]
1.6081121426075786
(6,)
(6,)
[-0.1013 -0.0216  0.1455  1.5735 -0.2366 -0.1489]
1.6080461612218964
(6,)
(6,)
[-0.1014 -0.0224  0.1447

1.602646502093912
(6,)
(6,)
[ 0.1016 -0.0583 -0.0733  0.963  -0.8437  0.954 ]
1.6035548433758322
(6,)
(6,)
[ 0.1109 -0.0593 -0.077   0.9565 -0.8504  0.9548]
1.6045365470499193
(6,)
(6,)
[ 0.1201 -0.0607 -0.0808  0.95   -0.8571  0.9554]
1.6055799354715892
(6,)
(6,)
[ 0.1291 -0.0623 -0.0846  0.9435 -0.8638  0.956 ]
1.6066706700169684
(6,)
(6,)
[ 0.1377 -0.0643 -0.0884  0.9369 -0.8705  0.9564]
1.6077932486538051
(6,)
(6,)
[ 0.146  -0.0668 -0.0921  0.9304 -0.8772  0.9568]
1.6089328669114251
(6,)
(6,)
[ 0.1537 -0.0697 -0.0958  0.9239 -0.884   0.9571]
1.6100772109123125
(6,)
(6,)
[ 0.1607 -0.073  -0.0994  0.9174 -0.8907  0.9573]
1.6112177321376822
(6,)
(6,)
[ 0.1672 -0.0769 -0.1029  0.9108 -0.8975  0.9574]
1.612350128507429
(6,)
(6,)
[ 0.1729 -0.0812 -0.1064  0.9042 -0.9042  0.9574]
1.6134740381645623
(6,)
(6,)
[ 0.178  -0.0862 -0.1098  0.8976 -0.911   0.9573]
1.614592181425496
(6,)
(6,)
[ 0.1825 -0.0917 -0.1132  0.891  -0.9178  0.9571]
1.6157092470223804
(6,)
(6,)
[ 0.1863 -0.0978 -0.1166  

1.6005978533573233
(6,)
(6,)
[ 1.0120e-01 -1.4000e-03 -3.2800e-02  2.5590e-01 -1.5517e+00 -2.7830e-01]
1.600539362010674
(6,)
(6,)
[ 1.0090e-01 -2.0000e-04 -3.1600e-02  2.5790e-01 -1.5497e+00 -2.8740e-01]
1.6004823947103597
(6,)
(6,)
[ 1.0050e-01  9.0000e-04 -3.0300e-02  2.5990e-01 -1.5476e+00 -2.9640e-01]
1.6004269461902445
(6,)
(6,)
[ 0.1002  0.0021 -0.029   0.262  -1.5455 -0.3054]
1.6003730111714003
(6,)
(6,)
[ 0.0999  0.0032 -0.0277  0.2641 -1.5433 -0.3144]
1.6003205843522637
(6,)
(6,)
[ 0.0996  0.0044 -0.0265  0.2664 -1.5411 -0.3234]
1.6002696603985649
(6,)
(6,)
[ 0.0992  0.0055 -0.0252  0.2686 -1.5388 -0.3323]
1.6002202339331204
(6,)
(6,)
[ 0.0989  0.0066 -0.0239  0.271  -1.5364 -0.3412]
1.6001722995254304
(6,)
(6,)
[ 0.0986  0.0077 -0.0226  0.2734 -1.534  -0.35  ]
1.6001258516811008
(6,)
(6,)
[ 0.0982  0.0088 -0.0213  0.2758 -1.5315 -0.3588]
1.6000808848310768
(6,)
(6,)
[ 0.0979  0.0099 -0.02    0.2784 -1.5289 -0.3676]
1.6000373933207388
(6,)
(6,)
[ 0.0976  0.011  -0.0188  0.280

1.6022334028729037
(6,)
(6,)
[-0.0375  0.0697  0.1554  1.2395 -0.5582 -0.83  ]
1.6022361223572863
(6,)
(6,)
[-0.0384  0.0694  0.1557  1.2453 -0.5523 -0.8252]
1.6022380939039036
(6,)
(6,)
[-0.0394  0.069   0.156   1.251  -0.5465 -0.8203]
1.6022392963051497
(6,)
(6,)
[-0.0402  0.0686  0.1562  1.2567 -0.5408 -0.8153]
1.6022397083795612
(6,)
(6,)
[-0.0411  0.0682  0.1564  1.2624 -0.535  -0.8103]
1.6022393090155145
(6,)
(6,)
[-0.042   0.0678  0.1567  1.268  -0.5293 -0.8052]
1.6022380772146918
(6,)
(6,)
[-0.0429  0.0674  0.1569  1.2736 -0.5237 -0.7999]
1.602235992135128
(6,)
(6,)
[-0.0437  0.067   0.1571  1.2791 -0.5181 -0.7947]
1.602233033133831
(6,)
(6,)
[-0.0445  0.0667  0.1573  1.2847 -0.5125 -0.7893]
1.6022291798087427
(6,)
(6,)
[-0.0454  0.0663  0.1575  1.2901 -0.5069 -0.7839]
1.6022244120400713
(6,)
(6,)
[-0.0462  0.0659  0.1576  1.2956 -0.5014 -0.7784]
1.6022187100307475
(6,)
(6,)
[-0.047   0.0655  0.1578  1.301  -0.4959 -0.7728]
1.6022120543460432
(6,)
(6,)
[-0.0478  0.0651  0.1579 

1.5942703586287692
(6,)
(6,)
[-0.0283  0.0422  0.0979  1.4414 -0.3511  0.5733]
1.5942589432623064
(6,)
(6,)
[-0.0284  0.0423  0.0976  1.4374 -0.3552  0.5809]
1.594247375074907
(6,)
(6,)
[-0.0285  0.0424  0.0972  1.4333 -0.3593  0.5884]
1.5942355746935186
(6,)
(6,)
[-0.0286  0.0424  0.0968  1.4291 -0.3634  0.5959]
1.5942234656799095
(6,)
(6,)
[-0.0288  0.0425  0.0964  1.4249 -0.3677  0.6033]
1.594210974885613
(6,)
(6,)
[-0.0289  0.0425  0.096   1.4207 -0.3719  0.6107]
1.5941980327683072
(6,)
(6,)
[-0.0291  0.0425  0.0956  1.4164 -0.3762  0.618 ]
1.5941845736679012
(6,)
(6,)
[-0.0293  0.0425  0.0951  1.412  -0.3806  0.6253]
1.5941705360416667
(6,)
(6,)
[-0.0295  0.0425  0.0947  1.4077 -0.385   0.6325]
1.5941558626582524
(6,)
(6,)
[-0.0297  0.0424  0.0943  1.4032 -0.3895  0.6396]
1.5941405007514677
(6,)
(6,)
[-0.0299  0.0424  0.0938  1.3987 -0.394   0.6467]
1.594124402135146
(6,)
(6,)
[-0.0301  0.0423  0.0933  1.3942 -0.3986  0.6537]
1.5941075232811583
(6,)
(6,)
[-0.0304  0.0422  0.0928  

1.62107211540967
(6,)
(6,)
[ 0.1461 -0.2065 -0.1396  0.468  -1.3351  0.7367]
1.6211464241907374
(6,)
(6,)
[ 0.1459 -0.2072 -0.1398  0.4628 -1.3403  0.7306]
1.6212416032429884
(6,)
(6,)
[ 0.1458 -0.2081 -0.1401  0.4577 -1.3453  0.7245]
1.621357791033239
(6,)
(6,)
[ 0.1457 -0.209  -0.1404  0.4526 -1.3504  0.7182]
1.621494980392972
(6,)
(6,)
[ 0.1457 -0.2101 -0.1406  0.4476 -1.3554  0.7119]
1.6216530068996389
(6,)
(6,)
[ 0.1458 -0.2112 -0.1409  0.4426 -1.3603  0.7055]
1.6218315388437767
(6,)
(6,)
[ 0.1459 -0.2125 -0.1412  0.4376 -1.3652  0.6991]
1.622030069348351
(6,)
(6,)
[ 0.1461 -0.2138 -0.1415  0.4327 -1.37    0.6925]
1.6222479111835058
(6,)
(6,)
[ 0.1463 -0.2153 -0.1418  0.4279 -1.3748  0.686 ]
1.6224841947608453
(6,)
(6,)
[ 0.1467 -0.2168 -0.1421  0.4231 -1.3796  0.6793]
1.6227378696933112
(6,)
(6,)
[ 0.147  -0.2184 -0.1424  0.4183 -1.3843  0.6726]
1.6230077101753795
(6,)
(6,)
[ 0.1474 -0.2201 -0.1427  0.4136 -1.389   0.6658]
1.6232923242779747
(6,)
(6,)
[ 0.1479 -0.2218 -0.143   0.

1.6085293838650694
(6,)
(6,)
[ 0.1139 -0.1819 -0.0529  0.2347 -1.5643 -0.1911]
1.6081392543588153
(6,)
(6,)
[ 0.1127 -0.1799 -0.0511  0.236  -1.5629 -0.2003]
1.6077523401478817
(6,)
(6,)
[ 0.1116 -0.1778 -0.0494  0.2374 -1.5614 -0.2096]
1.6073687616619374
(6,)
(6,)
[ 0.1104 -0.1757 -0.0477  0.2389 -1.5599 -0.2188]
1.6069886356565386
(6,)
(6,)
[ 0.1093 -0.1736 -0.046   0.2404 -1.5583 -0.2281]
1.6066120753202222
(6,)
(6,)
[ 0.1081 -0.1715 -0.0442  0.242  -1.5567 -0.2373]
1.6062391903750652
(6,)
(6,)
[ 0.1069 -0.1694 -0.0425  0.2436 -1.555  -0.2464]
1.6058700871703235
(6,)
(6,)
[ 0.1057 -0.1673 -0.0407  0.2454 -1.5532 -0.2556]
1.6055048687690823
(6,)
(6,)
[ 0.1045 -0.1652 -0.0389  0.2471 -1.5514 -0.2647]
1.6051436350277644
(6,)
(6,)
[ 0.1033 -0.1631 -0.0372  0.249  -1.5495 -0.2738]
1.6047864826682312
(6,)
(6,)
[ 0.102  -0.161  -0.0354  0.2509 -1.5475 -0.2829]
1.6044335053423562
(6,)
(6,)
[ 0.1008 -0.1589 -0.0336  0.2529 -1.5455 -0.2919]
1.604084793688832
(6,)
(6,)
[ 0.0995 -0.1568 -0.0318

1.5974019415150307
(6,)
(6,)
[-0.0666  0.0687  0.1544  1.1068 -0.6779 -0.9132]
1.5974145520973548
(6,)
(6,)
[-0.0667  0.0668  0.1554  1.1132 -0.6715 -0.9102]
1.5974273896575406
(6,)
(6,)
[-0.0668  0.0649  0.1564  1.1196 -0.6652 -0.9071]
1.5974405706744654
(6,)
(6,)
[-0.0669  0.0629  0.1574  1.1259 -0.6588 -0.9038]
1.5974542070774926
(6,)
(6,)
[-0.0669  0.061   0.1584  1.1322 -0.6525 -0.9005]
1.597468406000707
(6,)
(6,)
[-0.067   0.0589  0.1593  1.1385 -0.6462 -0.8971]
1.5974832695620425
(6,)
(6,)
[-0.067   0.0569  0.1602  1.1447 -0.6399 -0.8936]
1.5974988946671267
(6,)
(6,)
[-0.0671  0.0548  0.1612  1.151  -0.6337 -0.8901]
1.5975153728377862
(6,)
(6,)
[-0.0671  0.0527  0.1621  1.1572 -0.6275 -0.8864]
1.5975327900648786
(6,)
(6,)
[-0.0671  0.0505  0.163   1.1634 -0.6213 -0.8827]
1.5975512266851646
(6,)
(6,)
[-0.0671  0.0484  0.1638  1.1695 -0.6151 -0.8788]
1.5975707572817888
(6,)
(6,)
[-0.0672  0.0462  0.1647  1.1757 -0.609  -0.8749]
1.5975914506079048
(6,)
(6,)
[-0.0672  0.044   0.1655

(6,)
[-0.026  -0.2213  0.0444  1.3764 -0.4077  0.676 ]
1.6027749157683377
(6,)
(6,)
[-0.028  -0.22    0.0444  1.3717 -0.4124  0.6828]
1.6026338818948282
(6,)
(6,)
[-0.0299 -0.2186  0.0444  1.3669 -0.4173  0.6894]
1.6024924934269735
(6,)
(6,)
[-0.0317 -0.2172  0.0444  1.362  -0.4221  0.696 ]
1.6023506348285421
(6,)
(6,)
[-0.0334 -0.2159  0.0444  1.3572 -0.427   0.7026]
1.6022081947588924
(6,)
(6,)
[-0.035  -0.2145  0.0443  1.3522 -0.432   0.709 ]
1.602065066337452
(6,)
(6,)
[-0.0365 -0.2131  0.0442  1.3473 -0.4369  0.7154]
1.6019211471419015
(6,)
(6,)
[-0.038  -0.2117  0.0441  1.3423 -0.442   0.7218]
1.6017763390147874
(6,)
(6,)
[-0.0394 -0.2103  0.044   1.3372 -0.4471  0.728 ]
1.601630547734448
(6,)
(6,)
[-0.0407 -0.2089  0.0438  1.3321 -0.4522  0.7342]
1.6014836825916796
(6,)
(6,)
[-0.042  -0.2074  0.0436  1.327  -0.4574  0.7403]
1.6013356559024268
(6,)
(6,)
[-0.0431 -0.206   0.0435  1.3218 -0.4626  0.7463]
1.6011863824784733
(6,)
(6,)
[-0.0442 -0.2046  0.0432  1.3165 -0.4678  0.7523]

1.6560158623870207
(6,)
(6,)
[-0.2164  0.3177  0.1221  0.4035 -1.4249  0.6218]
1.65486290399687
(6,)
(6,)
[-0.2129  0.3147  0.1206  0.3991 -1.4292  0.6146]
1.6537292447188483
(6,)
(6,)
[-0.2093  0.3116  0.1192  0.3949 -1.4335  0.6074]
1.652614526530909
(6,)
(6,)
[-0.2058  0.3086  0.1177  0.3906 -1.4377  0.6001]
1.6515184047467728
(6,)
(6,)
[-0.2023  0.3056  0.1163  0.3865 -1.4419  0.5927]
1.6504405484775662
(6,)
(6,)
[-0.1988  0.3026  0.1148  0.3823 -1.446   0.5853]
1.6493806410439145
(6,)
(6,)
[-0.1953  0.2996  0.1134  0.3783 -1.4501  0.5778]
1.6483383803329974
(6,)
(6,)
[-0.1918  0.2967  0.112   0.3742 -1.4541  0.5703]
1.6473134790952315
(6,)
(6,)
[-0.1884  0.2937  0.1106  0.3703 -1.4581  0.5627]
1.6463056651752113
(6,)
(6,)
[-0.1849  0.2908  0.1092  0.3663 -1.462   0.555 ]
1.6453146816716975
(6,)
(6,)
[-0.1815  0.2878  0.1079  0.3625 -1.4658  0.5473]
1.6443402870220563
(6,)
(6,)
[-0.1781  0.2849  0.1065  0.3587 -1.4696  0.5396]
1.6433822550068695
(6,)
(6,)
[-0.1747  0.282   0.1051  

1.6211592020526973
(6,)
(6,)
[ 0.1652  0.0379  0.1411  0.7391 -1.0891 -0.9204]
1.6211123531628824
(6,)
(6,)
[ 0.1641  0.0381  0.1419  0.7456 -1.0826 -0.9228]
1.6210598271371772
(6,)
(6,)
[ 0.163   0.0383  0.1427  0.752  -1.0762 -0.9251]
1.6210016565790808
(6,)
(6,)
[ 0.1618  0.0385  0.1435  0.7585 -1.0697 -0.9273]
1.6209378817543656
(6,)
(6,)
[ 0.1606  0.0387  0.1443  0.7649 -1.0631 -0.9295]
1.6208685506862535
(6,)
(6,)
[ 0.1593  0.0389  0.1451  0.7714 -1.0566 -0.9315]
1.62079371924309
(6,)
(6,)
[ 0.158   0.0392  0.1458  0.7779 -1.0501 -0.9335]
1.6207134512179566
(6,)
(6,)
[ 0.1566  0.0394  0.1466  0.7845 -1.0435 -0.9353]
1.620627818400116
(6,)
(6,)
[ 0.1551  0.0397  0.1473  0.791  -1.0369 -0.9371]
1.620536900638107
(6,)
(6,)
[ 0.1536  0.04    0.148   0.7975 -1.0303 -0.9388]
1.6204407858941905
(6,)
(6,)
[ 0.1521  0.0403  0.1487  0.8041 -1.0237 -0.9404]
1.6203395702896815
(6,)
(6,)
[ 0.1505  0.0406  0.1494  0.8106 -1.0171 -0.9419]
1.6202333581410822
(6,)
(6,)
[ 0.1488  0.0409  0.1501  0

1.6139532720759124
(6,)
(6,)
[-0.0685  0.1085  0.1522  1.3827 -0.4353 -0.6811]
1.6140292293488099
(6,)
(6,)
[-0.069   0.1092  0.1527  1.3874 -0.4305 -0.6744]
1.6141041993742113
(6,)
(6,)
[-0.0695  0.1099  0.1533  1.3921 -0.4257 -0.6677]
1.6141779398200768
(6,)
(6,)
[-0.07    0.1106  0.1539  1.3967 -0.421  -0.6609]
1.6142502126046439
(6,)
(6,)
[-0.0704  0.1112  0.1544  1.4013 -0.4163 -0.654 ]
1.6143207847105618
(6,)
(6,)
[-0.0708  0.1117  0.155   1.4058 -0.4117 -0.6471]
1.6143894289507024
(6,)
(6,)
[-0.0712  0.1123  0.1556  1.4103 -0.4071 -0.6401]
1.6144559246780787
(6,)
(6,)
[-0.0716  0.1128  0.1562  1.4147 -0.4026 -0.633 ]
1.6145200584340633
(6,)
(6,)
[-0.0719  0.1133  0.1568  1.4191 -0.3981 -0.6259]
1.6145816245308906
(6,)
(6,)
[-0.0722  0.1137  0.1574  1.4235 -0.3937 -0.6187]
1.6146404255660312
(6,)
(6,)
[-0.0725  0.1141  0.158   1.4277 -0.3893 -0.6114]
1.614696272867184
(6,)
(6,)
[-0.0728  0.1145  0.1586  1.432  -0.3849 -0.6041]
1.614748986868018
(6,)
(6,)
[-0.0731  0.1148  0.1592 

1.6030778218092387
(6,)
(6,)
[ 0.1085 -0.0494  0.0405  1.4117 -0.3983  0.6344]
1.60328932780117
(6,)
(6,)
[ 0.1118 -0.0513  0.0383  1.4072 -0.4027  0.6414]
1.6035082635984712
(6,)
(6,)
[ 0.115  -0.0532  0.0361  1.4027 -0.4072  0.6485]
1.603733594102615
(6,)
(6,)
[ 0.1181 -0.0551  0.034   1.3981 -0.4118  0.6554]
1.6039641993425946
(6,)
(6,)
[ 0.1212 -0.057   0.0318  1.3935 -0.4163  0.6623]
1.6041988864046899
(6,)
(6,)
[ 0.1243 -0.0588  0.0296  1.3888 -0.421   0.6691]
1.6044364039315984
(6,)
(6,)
[ 0.1272 -0.0606  0.0275  1.3841 -0.4257  0.6759]
1.6046754589219536
(6,)
(6,)
[ 0.1301 -0.0623  0.0254  1.3793 -0.4304  0.6826]
1.6049147354336508
(6,)
(6,)
[ 0.1328 -0.064   0.0233  1.3745 -0.4352  0.6892]
1.6051529146793733
(6,)
(6,)
[ 0.1355 -0.0656  0.0212  1.3696 -0.44    0.6957]
1.6053886959094508
(6,)
(6,)
[ 0.1381 -0.0671  0.0191  1.3647 -0.4449  0.7022]
1.6056208174151632
(6,)
(6,)
[ 0.1406 -0.0686  0.017   1.3597 -0.4498  0.7086]
1.6058480769607453
(6,)
(6,)
[ 0.1429 -0.07    0.015   

1.6128703849226722
(6,)
(6,)
[ 0.1251 -0.1085 -0.0725  0.3486 -1.4719  0.5299]
1.6124893696134888
(6,)
(6,)
[ 0.1228 -0.1066 -0.0705  0.345  -1.4755  0.522 ]
1.6121222432533773
(6,)
(6,)
[ 0.1205 -0.1047 -0.0685  0.3414 -1.4792  0.5141]
1.6117691173140358
(6,)
(6,)
[ 0.1183 -0.103  -0.0665  0.3378 -1.4827  0.5061]
1.6114300580440304
(6,)
(6,)
[ 0.116  -0.1014 -0.0646  0.3343 -1.4863  0.4981]
1.6111050826688083
(6,)
(6,)
[ 0.1137 -0.0999 -0.0627  0.3309 -1.4897  0.49  ]
1.6107941565030908
(6,)
(6,)
[ 0.1114 -0.0985 -0.0607  0.3275 -1.4931  0.4819]
1.6104971911018147
(6,)
(6,)
[ 0.1091 -0.0972 -0.0589  0.3242 -1.4965  0.4737]
1.6102140435324654
(6,)
(6,)
[ 0.1068 -0.096  -0.057   0.3209 -1.4997  0.4655]
1.6099445168020317
(6,)
(6,)
[ 0.1045 -0.0949 -0.0552  0.3177 -1.503   0.4572]
1.6096883614198922
(6,)
(6,)
[ 0.1023 -0.0939 -0.0534  0.3145 -1.5061  0.4489]
1.6094452780278574
(6,)
(6,)
[ 0.1    -0.093  -0.0517  0.3114 -1.5093  0.4406]
1.609214920984227
(6,)
(6,)
[ 0.0978 -0.0922 -0.05  

1.6034626861833863
(6,)
(6,)
[-0.0063  0.0379  0.0947  0.6263 -1.1884 -0.8695]
1.6035129130331023
(6,)
(6,)
[-0.0066  0.0389  0.0956  0.6324 -1.1823 -0.8734]
1.603563926912941
(6,)
(6,)
[-0.007   0.0398  0.0965  0.6385 -1.1761 -0.8772]
1.6036156962839914
(6,)
(6,)
[-0.0074  0.0407  0.0975  0.6446 -1.17   -0.881 ]
1.6036681891261821
(6,)
(6,)
[-0.0077  0.0416  0.0984  0.6507 -1.1637 -0.8846]
1.603721372978837
(6,)
(6,)
[-0.0081  0.0425  0.0993  0.6569 -1.1575 -0.8882]
1.603775214982534
(6,)
(6,)
[-0.0085  0.0434  0.1003  0.6631 -1.1513 -0.8916]
1.6038296819221252
(6,)
(6,)
[-0.0088  0.0443  0.1012  0.6693 -1.145  -0.895 ]
1.6038847402707868
(6,)
(6,)
[-0.0092  0.0451  0.1021  0.6755 -1.1387 -0.8983]
1.6039403562350063
(6,)
(6,)
[-0.0096  0.046   0.1031  0.6818 -1.1323 -0.9015]
1.603996495800416
(6,)
(6,)
[-0.01    0.0468  0.104   0.6881 -1.126  -0.9046]
1.6040531247783052
(6,)
(6,)
[-0.0104  0.0476  0.1049  0.6944 -1.1196 -0.9077]
1.604110208852711
(6,)
(6,)
[-0.0108  0.0484  0.1058  0.

1.606083621796292
(6,)
(6,)
[-0.0976 -0.009   0.1488  1.5627 -0.2428 -0.2162]
1.6060219442983064
(6,)
(6,)
[-0.0977 -0.0097  0.1481  1.5642 -0.2414 -0.207 ]
1.6059596507595035
(6,)
(6,)
[-0.0979 -0.0105  0.1474  1.5656 -0.2399 -0.1977]
1.6058967585056523
(6,)
(6,)
[-0.098  -0.0113  0.1467  1.5669 -0.2385 -0.1885]
1.6058332849732602
(6,)
(6,)
[-0.0981 -0.012   0.146   1.5682 -0.2372 -0.1791]
1.6057692476983603
(6,)
(6,)
[-0.0983 -0.0128  0.1452  1.5694 -0.236  -0.1698]
1.6057046643054425
(6,)
(6,)
[-0.0984 -0.0135  0.1445  1.5706 -0.2348 -0.1605]
1.605639552496524
(6,)
(6,)
[-0.0985 -0.0143  0.1437  1.5716 -0.2337 -0.1511]
1.6055739300404654
(6,)
(6,)
[-0.0986 -0.015   0.143   1.5727 -0.2327 -0.1418]
1.6055078147624309
(6,)
(6,)
[-0.0987 -0.0158  0.1422  1.5736 -0.2317 -0.1324]
1.6054412245336303
(6,)
(6,)
[-0.0988 -0.0165  0.1415  1.5745 -0.2308 -0.123 ]
1.605374177261136
(6,)
(6,)
[-0.0989 -0.0173  0.1407  1.5753 -0.23   -0.1136]
1.6053066908780282
(6,)
(6,)
[-0.0989 -0.018   0.1399  

1.6321366182469021
(6,)
(6,)
[ 0.173  -0.236  -0.1656  0.7379 -1.0698  0.9283]
1.6322559903441192
(6,)
(6,)
[ 0.1709 -0.238  -0.1661  0.7314 -1.0763  0.926 ]
1.632322059349013
(6,)
(6,)
[ 0.1688 -0.2396 -0.1664  0.7249 -1.0829  0.9235]
1.6323389822300371
(6,)
(6,)
[ 0.1668 -0.2409 -0.1667  0.7184 -1.0893  0.9209]
1.6323107460285815
(6,)
(6,)
[ 0.1648 -0.242  -0.1668  0.712  -1.0958  0.9183]
1.6322411434168898
(6,)
(6,)
[ 0.1628 -0.2427 -0.1669  0.7055 -1.1023  0.9155]
1.6321337595364493
(6,)
(6,)
[ 0.1609 -0.2433 -0.167   0.6991 -1.1087  0.9127]
1.6319919669565344
(6,)
(6,)
[ 0.159  -0.2436 -0.1669  0.6927 -1.1151  0.9098]
1.6318189263409295
(6,)
(6,)
[ 0.1571 -0.2437 -0.1668  0.6863 -1.1215  0.9067]
1.6316175910111492
(6,)
(6,)
[ 0.1553 -0.2437 -0.1667  0.68   -1.1278  0.9036]
1.6313907140660298
(6,)
(6,)
[ 0.1536 -0.2434 -0.1665  0.6736 -1.1342  0.9004]
1.631140857080132
(6,)
(6,)
[ 0.1519 -0.243  -0.1662  0.6673 -1.1405  0.8972]
1.6308703996802059
(6,)
(6,)
[ 0.1503 -0.2425 -0.1659 

1.5983810983490574
(6,)
(6,)
[ 0.1051  0.0218 -0.013   0.2942 -1.508  -0.4271]
1.5983484754834685
(6,)
(6,)
[ 0.1047  0.0228 -0.0117  0.2972 -1.505  -0.4356]
1.598317246675225
(6,)
(6,)
[ 0.1044  0.0238 -0.0103  0.3003 -1.5019 -0.444 ]
1.5982874061961898
(6,)
(6,)
[ 0.104   0.0249 -0.009   0.3034 -1.4988 -0.4524]
1.598258948070153
(6,)
(6,)
[ 0.1037  0.0259 -0.0076  0.3066 -1.4955 -0.4608]
1.598231866060608
(6,)
(6,)
[ 0.1033  0.0269 -0.0063  0.3098 -1.4923 -0.4691]
1.598206153658472
(6,)
(6,)
[ 0.103   0.0279 -0.0049  0.3131 -1.489  -0.4773]
1.5981818040698417
(6,)
(6,)
[ 0.1026  0.0289 -0.0036  0.3164 -1.4856 -0.4856]
1.5981588102037525
(6,)
(6,)
[ 0.1022  0.0299 -0.0022  0.3198 -1.4821 -0.4937]
1.598137164659951
(6,)
(6,)
[ 1.0180e-01  3.0900e-02 -8.0000e-04  3.2330e-01 -1.4786e+00 -5.0180e-01]
1.5981168597167787
(6,)
(6,)
[ 1.0150e-01  3.1900e-02  5.0000e-04  3.2680e-01 -1.4751e+00 -5.0990e-01]
1.598097887319143
(6,)
(6,)
[ 0.1011  0.0329  0.0019  0.3304 -1.4715 -0.5179]
1.59808023

1.6000284622169245
(6,)
(6,)
[-0.0668  0.0565  0.1605  1.4363 -0.3542 -0.5817]
1.5999846925860886
(6,)
(6,)
[-0.0672  0.0561  0.1603  1.4403 -0.3501 -0.5741]
1.5999395435843238
(6,)
(6,)
[-0.0676  0.0557  0.1601  1.4443 -0.3461 -0.5664]
1.599893017976733
(6,)
(6,)
[-0.068   0.0553  0.1598  1.4482 -0.3421 -0.5587]
1.5998451195376855
(6,)
(6,)
[-0.0683  0.0549  0.1596  1.452  -0.3382 -0.551 ]
1.5997958530465697
(6,)
(6,)
[-0.0686  0.0545  0.1593  1.4559 -0.3344 -0.5431]
1.599745224282586
(6,)
(6,)
[-0.0689  0.054   0.1591  1.4596 -0.3305 -0.5353]
1.5996932400186508
(6,)
(6,)
[-0.0692  0.0536  0.1588  1.4633 -0.3268 -0.5273]
1.5996399080145907
(6,)
(6,)
[-0.0695  0.0532  0.1585  1.467  -0.3231 -0.5193]
1.599585237009554
(6,)
(6,)
[-0.0697  0.0528  0.1582  1.4705 -0.3194 -0.5113]
1.5995292367137182
(6,)
(6,)
[-0.07    0.0524  0.1579  1.4741 -0.3159 -0.5032]
1.5994719177993926
(6,)
(6,)
[-0.0702  0.052   0.1576  1.4776 -0.3123 -0.4951]
1.5994132918916835
(6,)
(6,)
[-0.0704  0.0516  0.1573  

1.5940521881763499
(6,)
(6,)
[-0.0279  0.0646  0.1092  1.3547 -0.4339  0.7075]
1.5940381194725788
(6,)
(6,)
[-0.0288  0.0643  0.1088  1.3498 -0.4389  0.7139]
1.594021123631617
(6,)
(6,)
[-0.0297  0.0639  0.1083  1.3447 -0.444   0.7202]
1.5940012873280736
(6,)
(6,)
[-0.0306  0.0635  0.1077  1.3397 -0.4491  0.7265]
1.593978701535991
(6,)
(6,)
[-0.0314  0.0631  0.1072  1.3346 -0.4542  0.7327]
1.5939534608610666
(6,)
(6,)
[-0.0322  0.0627  0.1066  1.3295 -0.4594  0.7388]
1.5939256629591914
(6,)
(6,)
[-0.0329  0.0623  0.1059  1.3243 -0.4646  0.7449]
1.5938954080390577
(6,)
(6,)
[-0.0336  0.0619  0.1053  1.3191 -0.4698  0.7508]
1.5938627984466374
(6,)
(6,)
[-0.0342  0.0615  0.1046  1.3138 -0.4751  0.7567]
1.5938279383295695
(6,)
(6,)
[-0.0348  0.0611  0.1039  1.3085 -0.4805  0.7626]
1.5937909333796587
(6,)
(6,)
[-0.0353  0.0607  0.1032  1.3032 -0.4858  0.7683]
1.5937518906524863
(6,)
(6,)
[-0.0357  0.0602  0.1024  1.2978 -0.4912  0.774 ]
1.5937109184635825
(6,)
(6,)
[-0.0362  0.0598  0.1016 

1.64458326708541
(6,)
(6,)
[ 0.264  -0.2804 -0.1397  0.2536 -1.5442  0.2969]
1.644107640074641
(6,)
(6,)
[ 0.2632 -0.279  -0.1384  0.2515 -1.5462  0.2878]
1.6436232097157644
(6,)
(6,)
[ 0.2623 -0.2776 -0.1372  0.2495 -1.5482  0.2788]
1.6431304686825596
(6,)
(6,)
[ 0.2615 -0.2762 -0.136   0.2476 -1.5501  0.2697]
1.6426298975588987
(6,)
(6,)
[ 0.2606 -0.2747 -0.1347  0.2457 -1.5519  0.2606]
1.642121964797708
(6,)
(6,)
[ 0.2597 -0.2732 -0.1334  0.2439 -1.5537  0.2514]
1.641607126717469
(6,)
(6,)
[ 0.2588 -0.2717 -0.1321  0.2422 -1.5554  0.2423]
1.6410858275329347
(6,)
(6,)
[ 0.2579 -0.2701 -0.1308  0.2405 -1.5571  0.2331]
1.6405584994154008
(6,)
(6,)
[ 0.257  -0.2685 -0.1295  0.2389 -1.5586  0.2239]
1.6400255625803206
(6,)
(6,)
[ 0.256  -0.2669 -0.1281  0.2373 -1.5602  0.2146]
1.6394874253979126
(6,)
(6,)
[ 0.255  -0.2652 -0.1268  0.2359 -1.5616  0.2054]
1.6389444845250476
(6,)
(6,)
[ 0.254  -0.2636 -0.1254  0.2344 -1.563   0.1961]
1.6383971250550164
(6,)
(6,)
[ 0.253  -0.2619 -0.124   0.

1.6477526282078399
(6,)
(6,)
[-0.0772  0.4069  0.1793  0.8117 -0.9679 -0.957 ]
1.6480727121471805
(6,)
(6,)
[-0.079   0.4081  0.1794  0.8183 -0.9611 -0.958 ]
1.6483376737005406
(6,)
(6,)
[-0.0808  0.4091  0.1795  0.825  -0.9543 -0.959 ]
1.6485496515289784
(6,)
(6,)
[-0.0827  0.4097  0.1796  0.8316 -0.9475 -0.9599]
1.6487108082498325
(6,)
(6,)
[-0.0845  0.4102  0.1797  0.8383 -0.9407 -0.9607]
1.6488233179532026
(6,)
(6,)
[-0.0864  0.4105  0.1798  0.8449 -0.9338 -0.9614]
1.6488893557829354
(6,)
(6,)
[-0.0883  0.4105  0.18    0.8516 -0.927  -0.962 ]
1.6489110893176913
(6,)
(6,)
[-0.0902  0.4104  0.1801  0.8583 -0.9202 -0.9625]
1.64889067151311
(6,)
(6,)
[-0.0922  0.4101  0.1802  0.865  -0.9134 -0.9629]
1.6488302349910986
(6,)
(6,)
[-0.0942  0.4096  0.1803  0.8716 -0.9066 -0.9633]
1.6487318874858843
(6,)
(6,)
[-0.0962  0.4089  0.1804  0.8783 -0.8998 -0.9635]
1.6485977082785737
(6,)
(6,)
[-0.0982  0.4081  0.1805  0.885  -0.893  -0.9636]
1.6484297454716972
(6,)
(6,)
[-0.1003  0.4071  0.1806 

1.5991890881468516
(6,)
(6,)
[-0.2087  0.0206  0.1503  1.5655 -0.1994  0.0144]
1.598783674013506
(6,)
(6,)
[-0.2065  0.0189  0.1493  1.5654 -0.1995  0.024 ]
1.5983808536132416
(6,)
(6,)
[-0.2043  0.0172  0.1484  1.5652 -0.1997  0.0335]
1.5979806784547839
(6,)
(6,)
[-0.2021  0.0155  0.1474  1.5649 -0.1999  0.0431]
1.5975832005386505
(6,)
(6,)
[-0.1998  0.0139  0.1465  1.5646 -0.2002  0.0527]
1.5971884724804828
(6,)
(6,)
[-0.1976  0.0122  0.1455  1.5641 -0.2006  0.0622]
1.5967965476358452
(6,)
(6,)
[-0.1954  0.0105  0.1445  1.5637 -0.2011  0.0718]
1.5964074802271737
(6,)
(6,)
[-0.1931  0.0088  0.1435  1.5631 -0.2016  0.0813]
1.596021325473457
(6,)
(6,)
[-0.1909  0.0072  0.1424  1.5625 -0.2022  0.0909]
1.5956381397224935
(6,)
(6,)
[-0.1886  0.0055  0.1414  1.5618 -0.2028  0.1004]
1.5952579805867158
(6,)
(6,)
[-0.1863  0.0038  0.1403  1.5611 -0.2035  0.1099]
1.5948809070828172
(6,)
(6,)
[-0.184   0.0021  0.1392  1.5603 -0.2043  0.1194]
1.5945069797751956
(6,)
(6,)
[-1.8170e-01  4.0000e-04 

1.661832844690922
(6,)
(6,)
[ 0.2832 -0.3782 -0.1952  0.662  -1.1097  0.9114]
1.660656245458754
(6,)
(6,)
[ 0.2789 -0.3767 -0.1941  0.6556 -1.1161  0.9082]
1.6594680561805266
(6,)
(6,)
[ 0.2747 -0.375  -0.1928  0.6493 -1.1225  0.9049]
1.6582707439345987
(6,)
(6,)
[ 0.2707 -0.373  -0.1916  0.643  -1.1289  0.9016]
1.6570665302089553
(6,)
(6,)
[ 0.2668 -0.371  -0.1903  0.6368 -1.1352  0.8981]
1.6558574131960448
(6,)
(6,)
[ 0.2631 -0.3688 -0.189   0.6305 -1.1416  0.8945]
1.6546451888259588
(6,)
(6,)
[ 0.2595 -0.3664 -0.1877  0.6243 -1.1478  0.8909]
1.653431470305723
(6,)
(6,)
[ 0.2559 -0.364  -0.1863  0.6181 -1.1541  0.8872]
1.6522177060777588
(6,)
(6,)
[ 0.2525 -0.3614 -0.185   0.612  -1.1603  0.8834]
1.6510051962024535
(6,)
(6,)
[ 0.2492 -0.3588 -0.1835  0.6058 -1.1665  0.8795]
1.649795107226478
(6,)
(6,)
[ 0.246  -0.356  -0.1821  0.5997 -1.1727  0.8755]
1.6485884856301665
(6,)
(6,)
[ 0.2429 -0.3532 -0.1807  0.5936 -1.1789  0.8714]
1.647386269963174
(6,)
(6,)
[ 0.2398 -0.3503 -0.1792  0.

1.5824692702008927
(6,)
(6,)
[ 0.0117 -0.04    0.0409  0.3243 -1.4477 -0.5475]
1.5824334072730242
(6,)
(6,)
[ 0.0114 -0.0386  0.0419  0.3281 -1.4438 -0.5553]
1.5823993496469673
(6,)
(6,)
[ 0.0112 -0.0372  0.0429  0.332  -1.4399 -0.5631]
1.5823671081471207
(6,)
(6,)
[ 0.0109 -0.0358  0.0439  0.3359 -1.4359 -0.5709]
1.5823366928930762
(6,)
(6,)
[ 0.0107 -0.0344  0.0448  0.3399 -1.4319 -0.5785]
1.5823081132847316
(6,)
(6,)
[ 0.0104 -0.033   0.0458  0.3439 -1.4278 -0.5861]
1.5822813779873577
(6,)
(6,)
[ 0.0101 -0.0315  0.0468  0.348  -1.4236 -0.5937]
1.5822564949165263
(6,)
(6,)
[ 0.0099 -0.0301  0.0478  0.3522 -1.4194 -0.6012]
1.5822334712229853
(6,)
(6,)
[ 0.0096 -0.0287  0.0488  0.3564 -1.4152 -0.6086]
1.582212313277471
(6,)
(6,)
[ 0.0094 -0.0273  0.0498  0.3606 -1.4109 -0.616 ]
1.5821930266554667
(6,)
(6,)
[ 0.0091 -0.0259  0.0508  0.3649 -1.4065 -0.6234]
1.5821756161219656
(6,)
(6,)
[ 0.0088 -0.0245  0.0518  0.3693 -1.4021 -0.6306]
1.5821600856162403
(6,)
(6,)
[ 0.0086 -0.0231  0.0528

1.5864318344149368
(6,)
(6,)
[-0.0293  0.0648  0.1435  0.9246 -0.8405 -0.9643]
1.5864940608350806
(6,)
(6,)
[-0.03    0.065   0.1443  0.9313 -0.8337 -0.9636]
1.586555654796262
(6,)
(6,)
[-0.0306  0.0652  0.1451  0.938  -0.8269 -0.9629]
1.5866166006033402
(6,)
(6,)
[-0.0312  0.0653  0.1459  0.9447 -0.8201 -0.9621]
1.5866768833513643
(6,)
(6,)
[-0.0319  0.0654  0.1466  0.9514 -0.8134 -0.9612]
1.5867364888940525
(6,)
(6,)
[-0.0325  0.0655  0.1474  0.9581 -0.8066 -0.9602]
1.5867954038105831
(6,)
(6,)
[-0.0331  0.0656  0.1482  0.9648 -0.7999 -0.9591]
1.586853615370931
(6,)
(6,)
[-0.0338  0.0656  0.1489  0.9715 -0.7931 -0.9579]
1.5869111114998358
(6,)
(6,)
[-0.0344  0.0657  0.1497  0.9782 -0.7864 -0.9566]
1.586967880739759
(6,)
(6,)
[-0.0351  0.0657  0.1504  0.9848 -0.7797 -0.9553]
1.587023912212881
(6,)
(6,)
[-0.0358  0.0657  0.1511  0.9915 -0.7729 -0.9538]
1.5870791955824293
(6,)
(6,)
[-0.0364  0.0656  0.1519  0.9981 -0.7662 -0.9522]
1.5871337210135337
(6,)
(6,)
[-0.0371  0.0656  0.1526  1

1.5805329851746917
(6,)
(6,)
[-0.0915 -0.0615  0.0775  1.469  -0.2881  0.4888]
1.580464126825388
(6,)
(6,)
[-0.0912 -0.0621  0.0762  1.4656 -0.2915  0.497 ]
1.5803957316624295
(6,)
(6,)
[-0.0909 -0.0627  0.075   1.4621 -0.295   0.5052]
1.5803277994384277
(6,)
(6,)
[-0.0905 -0.0633  0.0738  1.4585 -0.2985  0.5133]
1.5802603289899364
(6,)
(6,)
[-0.0902 -0.0639  0.0725  1.4549 -0.3021  0.5214]
1.580193318192263
(6,)
(6,)
[-0.0898 -0.0645  0.0713  1.4512 -0.3058  0.5294]
1.5801267639122394
(6,)
(6,)
[-0.0895 -0.065   0.07    1.4474 -0.3095  0.5374]
1.5800606619589705
(6,)
(6,)
[-0.0891 -0.0656  0.0688  1.4436 -0.3132  0.5454]
1.579995007032625
(6,)
(6,)
[-0.0888 -0.0662  0.0675  1.4398 -0.317   0.5532]
1.57992979267126
(6,)
(6,)
[-0.0884 -0.0668  0.0663  1.4359 -0.3209  0.5611]
1.5798650111957713
(6,)
(6,)
[-0.088  -0.0673  0.065   1.4319 -0.3248  0.5688]
1.5798006536530995
(6,)
(6,)
[-0.0876 -0.0679  0.0637  1.4279 -0.3288  0.5765]
1.579736709757773
(6,)
(6,)
[-0.0872 -0.0685  0.0625  1.4

1.5982988617302705
(6,)
(6,)
[ 0.1201 -0.1841 -0.1514  0.46   -1.2995  0.7635]
1.5979762947790352
(6,)
(6,)
[ 0.12   -0.1819 -0.1509  0.4546 -1.3049  0.7576]
1.5976583832037055
(6,)
(6,)
[ 0.12   -0.1797 -0.1505  0.4493 -1.3101  0.7516]
1.5973451623146646
(6,)
(6,)
[ 0.12   -0.1775 -0.15    0.444  -1.3154  0.7455]
1.5970366495024855
(6,)
(6,)
[ 0.12   -0.1754 -0.1496  0.4387 -1.3206  0.7394]
1.5967328461402934
(6,)
(6,)
[ 0.12   -0.1732 -0.1491  0.4335 -1.3257  0.7331]
1.5964337393533905
(6,)
(6,)
[ 0.12   -0.171  -0.1486  0.4284 -1.3308  0.7268]
1.5961393036610625
(6,)
(6,)
[ 0.1201 -0.1688 -0.1481  0.4233 -1.3359  0.7205]
1.5958495024960133
(6,)
(6,)
[ 0.1201 -0.1667 -0.1477  0.4182 -1.3409  0.714 ]
1.5955642896068936
(6,)
(6,)
[ 0.1202 -0.1646 -0.1472  0.4132 -1.3458  0.7075]
1.5952836103495411
(6,)
(6,)
[ 0.1203 -0.1624 -0.1467  0.4082 -1.3508  0.701 ]
1.595007402872673
(6,)
(6,)
[ 0.1204 -0.1603 -0.1461  0.4033 -1.3556  0.6943]
1.5947355992034569
(6,)
(6,)
[ 0.1205 -0.1582 -0.1456

1.5785041259600876
(6,)
(6,)
[ 0.1019  0.0655  0.046   0.4372 -1.3163 -0.7424]
1.5785262074089217
(6,)
(6,)
[ 0.1014  0.0663  0.0475  0.4424 -1.311  -0.7485]
1.5785491798065068
(6,)
(6,)
[ 0.1008  0.067   0.049   0.4477 -1.3057 -0.7546]
1.578573018087761
(6,)
(6,)
[ 0.1002  0.0678  0.0505  0.4529 -1.3004 -0.7606]
1.5785976966685016
(6,)
(6,)
[ 0.0997  0.0685  0.052   0.4583 -1.2951 -0.7665]
1.578623189465142
(6,)
(6,)
[ 0.0991  0.0693  0.0534  0.4636 -1.2897 -0.7723]
1.5786494699162275
(6,)
(6,)
[ 0.0985  0.07    0.0549  0.469  -1.2842 -0.778 ]
1.5786765110057384
(6,)
(6,)
[ 0.0979  0.0707  0.0564  0.4745 -1.2787 -0.7837]
1.5787042852883113
(6,)
(6,)
[ 0.0973  0.0714  0.0579  0.4799 -1.2732 -0.7893]
1.5787327649162652
(6,)
(6,)
[ 0.0967  0.0721  0.0594  0.4855 -1.2676 -0.7948]
1.5787619216685065
(6,)
(6,)
[ 0.096   0.0728  0.0609  0.491  -1.262  -0.8003]
1.578791726981171
(6,)
(6,)
[ 0.0954  0.0735  0.0624  0.4966 -1.2564 -0.8056]
1.5788221519802839
(6,)
(6,)
[ 0.0947  0.0741  0.0639  

1.5799431786083014
(6,)
(6,)
[-0.0852  0.0533  0.1661  1.4929 -0.2489 -0.4097]
1.5798555687831817
(6,)
(6,)
[-0.0852  0.0529  0.1656  1.4957 -0.246  -0.4009]
1.5797663326411702
(6,)
(6,)
[-0.0852  0.0525  0.1651  1.4985 -0.2432 -0.3922]
1.5796754922674476
(6,)
(6,)
[-0.0851  0.052   0.1647  1.5012 -0.2405 -0.3834]
1.579583070656708
(6,)
(6,)
[-0.0851  0.0516  0.1641  1.5038 -0.2378 -0.3745]
1.5794890916999815
(6,)
(6,)
[-0.085   0.0512  0.1636  1.5064 -0.2352 -0.3656]
1.5793935801721173
(6,)
(6,)
[-0.0849  0.0508  0.1631  1.5089 -0.2326 -0.3567]
1.5792965617195287
(6,)
(6,)
[-0.0847  0.0504  0.1626  1.5113 -0.2301 -0.3477]
1.5791980628486078
(6,)
(6,)
[-0.0846  0.05    0.162   1.5137 -0.2277 -0.3388]
1.5790981109146498
(6,)
(6,)
[-0.0844  0.0495  0.1615  1.5161 -0.2253 -0.3297]
1.578996734111655
(6,)
(6,)
[-0.0842  0.0491  0.1609  1.5183 -0.223  -0.3207]
1.5788939614628115
(6,)
(6,)
[-0.0839  0.0487  0.1604  1.5205 -0.2208 -0.3116]
1.5787898228118824
(6,)
(6,)
[-0.0837  0.0483  0.1598 

1.5861480025948076
(6,)
(6,)
[ 0.1138  0.1728  0.0549  0.9532 -0.7969  0.9626]
1.5863886700113115
(6,)
(6,)
[ 0.1205  0.1701  0.0515  0.9466 -0.8038  0.9635]
1.5861307456167253
(6,)
(6,)
[ 0.1258  0.1636  0.0477  0.94   -0.8107  0.9644]
1.585495178961105
(6,)
(6,)
[ 0.13    0.1538  0.0435  0.9334 -0.8176  0.9653]
1.58467743508691
(6,)
(6,)
[ 0.1336  0.1417  0.039   0.9267 -0.8245  0.966 ]
1.5838471549383581
(6,)
(6,)
[ 0.1368  0.1286  0.0343  0.92   -0.8315  0.9666]
1.5831071725358852
(6,)
(6,)
[ 0.14    0.1151  0.0294  0.9133 -0.8385  0.9671]
1.5825050625788475
(6,)
(6,)
[ 0.1431  0.1018  0.0245  0.9066 -0.8455  0.9676]
1.582056836976796
(6,)
(6,)
[ 0.1463  0.0887  0.0196  0.8999 -0.8525  0.9679]
1.5817638132324081
(6,)
(6,)
[ 0.1495  0.076   0.0146  0.8931 -0.8594  0.9681]
1.5816213933080248
(6,)
(6,)
[ 0.1529  0.0637  0.0097  0.8864 -0.8664  0.9683]
1.5816228818745681
(6,)
(6,)
[ 0.1563  0.0519  0.0048  0.8797 -0.8734  0.9683]
1.5817608676173032
(6,)
(6,)
[ 1.599e-01  4.040e-02 -1.0

KeyboardInterrupt: 

In [4]:
[70,-70,312,-1,-1,312]

[70, -70, 312, -1, -1, 312]

In [9]:
import sympy as sp
import numpy as np
from sympy.matrices import matrix_multiply_elementwise

def make_usable(string):
    # Find PI and make it usable
    string = string.replace('3.14159265358979',  'np.pi')
    string = string.replace('1.5707963267949', 'np.pi/2.')
    # Find super small numbers and make them zero
    string = string.replace('6.12323399573677e-17', '0.')
    string = string.replace('3.74939945665464e-33', '0.')
    string = string.replace('2.29584502165847e-49', '0.')
    string = string.replace('1.40579962855621e-65', '0.')
    string = string.replace('1.22464679914735e-16', '0.')
    string = string.replace('3.06161699786838e-17', '0.')
    string = string.replace('1.53080849893419e-17', '0.')
    string = string.replace('1.40579962855621e-65', '0.')
    # Find all q* and make them usable
    string = string.replace('q0', 'q[0]')
    string = string.replace('q1', 'q[1]')
    string = string.replace('q2', 'q[2]')
    string = string.replace('q3', 'q[3]')
    string = string.replace('q4', 'q[4]')
    string = string.replace('q5', 'q[5]')
    string = string.replace('q6', 'q[6]')
    # Remove all spaces
    string = string.replace(' ', '')
    return string

def calc_transform():
    # set up our joint angle symbols (6th angle doesn't affect any kinematics)
    q = [sp.Symbol('q0'), sp.Symbol('q1'), sp.Symbol('q2'), sp.Symbol('q3'),
         sp.Symbol('q4'), sp.Symbol('q5'), sp.Symbol('q6')]
    # set up our arm segment length symbols
    l1 = sp.Symbol('l0')
    l2 = sp.Symbol('l1')
    l3 = sp.Symbol('l2')
    l4 = sp.Symbol('l3')

    Torg0 = sp.Matrix([[1, 0, 0, 0],
                       [0, 1, 0, 0],
                       [0, 0, 1, 0],
                       [0, 0, 0, 1]])
 
    T01 = sp.Matrix([[sp.cos(q[1]),0, -sp.sin(q[1]), 0],
                    [sp.sin(q[1]), 0, sp.cos(q[1]), 0],
                    [0, -1, 0, l1],
                    [0, 0, 0, 1]])
  
    T12 = sp.Matrix([[sp.cos(q[2]), 0, sp.sin(q[2]), 0],
                    [sp.sin(q[2]), 0, -sp.cos(q[2]), 0],
                    [0, 1, 0, 0],
                    [0, 0, 0, 1]])
 
    T23 = sp.Matrix([[sp.cos(q[3]), 0, -sp.sin(q[3]), 0],
                    [sp.sin(q[3]), 0, sp.cos(q[3]), 0],
                    [0, 1, 0,l2],
                    [0, 0, 0, 1]])

    T34 = sp.Matrix([[sp.cos(q[4]), 0, -sp.sin(q[4]), 0],
                    [sp.sin(q[4]), 0, -sp.cos(q[4]), 0],
                    [0, 1, 0, 0],
                    [0, 0, 0, 1]])

    T45 = sp.Matrix([[sp.cos(q[5]), 0, -sp.sin(q[5]), 0],
                    [sp.sin(q[5]), 0, sp.cos(q[5]), 0],
                    [0, 1, 0, l3],
                    [0, 0, 0, 1]])
    
    T56 = sp.Matrix([[sp.cos(q[0]), 0, sp.sin(q[0]), 0],
                    [sp.sin(q[0]), 0, -sp.cos(q[0]), 0],
                    [0, 1, 0, 0],
                    [0, 0, 0, 1]])

    T67 = sp.Matrix([[sp.cos(q[6]), -sp.sin(q[6]), 0, 0],
                    [sp.sin(q[6]), sp.cos(q[6]), 0, 0],
                    [0, 0, 1, l4],
                    [0, 0, 0, 1]])

    ToTorg0 = Torg0*sp.Matrix([0,0,1,0])
    TxTorg0 = Torg0*sp.Matrix([0,0,0,1])
    ToTorg0.row_del(3)
    TxTorg0.row_del(3)

    T_01 = Torg0*T01
    To01  = T_01*sp.Matrix([0,0,1,0])
    Tx01  = T_01*sp.Matrix([0,0,0,1])
    To01.row_del(3)
    Tx01.row_del(3)

    T_02 = Torg0*T01*T12
    To02  = T_02*sp.Matrix([0,0,1,0])
    Tx02  = T_02*sp.Matrix([0,0,0,1])
    To02.row_del(3)
    Tx02.row_del(3)

    T_03 = Torg0*T01*T12*T23
    To03  = T_03*sp.Matrix([0,0,1,0])
    Tx03  = T_03*sp.Matrix([0,0,0,1])
    To03.row_del(3)
    Tx03.row_del(3)

    T_04 = Torg0*T01*T12*T23*T34
    To04  = T_04*sp.Matrix([0,0,1,0])
    Tx04  = T_04*sp.Matrix([0,0,0,1])
    To04.row_del(3)
    Tx04.row_del(3)

    T_05 = Torg0*T01*T12*T23*T34*T45
    To05  = T_05*sp.Matrix([0,0,1,0])
    Tx05  = T_05*sp.Matrix([0,0,0,1])
    To05.row_del(3)
    Tx05.row_del(3)

    T_06 = Torg0*T01*T12*T23*T34*T45*T56
    To06  = T_06*sp.Matrix([0,0,1,0])
    Tx06  = T_06*sp.Matrix([0,0,0,1])
    To06.row_del(3)
    Tx06.row_del(3)

    T_07 = Torg0*T01*T12*T23*T34*T45*T56*T67
    To07  = T_07*sp.Matrix([0,0,1,0])
    Tx07  = T_07*sp.Matrix([0,0,0,1])
    To07.row_del(3)
    Tx07.row_del(3)

    Jbuff = ToTorg0.cross(Tx07 - TxTorg0)
    print(Jbuff)
    print(Jbuff.shape)
    print('\n# q1')
    print('J[{}][{}]={}'.format(0, 0, make_usable(str(sp.simplify(Jbuff[0])))))
    print('J[{}][{}]={}'.format(1, 0, make_usable(str(sp.simplify(Jbuff[1])))))
    print('J[{}][{}]={}'.format(2, 0, make_usable(str(sp.simplify(Jbuff[2])))))
    print('J[{}][{}]={}'.format(3, 0, make_usable(str(sp.simplify(ToTorg0[0])))))
    print('J[{}][{}]={}'.format(4, 0, make_usable(str(sp.simplify(ToTorg0[1])))))
    print('J[{}][{}]={}'.format(5, 0, make_usable(str(sp.simplify(ToTorg0[2])))))
    print('\n# q2')
    Jbuff = To01.cross(Tx07 - Tx01)
    print('J[{}][{}]={}'.format(0, 1, make_usable(str(sp.simplify(Jbuff[0])))))
    print('J[{}][{}]={}'.format(1, 1, make_usable(str(sp.simplify(Jbuff[1])))))
    print('J[{}][{}]={}'.format(2, 1, make_usable(str(sp.simplify(Jbuff[2])))))
    print('J[{}][{}]={}'.format(3, 1, make_usable(str(sp.simplify(To01[0])))))
    print('J[{}][{}]={}'.format(4, 1, make_usable(str(sp.simplify(To01[1])))))
    print('J[{}][{}]={}'.format(5, 1, make_usable(str(sp.simplify(To01[2])))))
    print('\n# q3')
    Jbuff = To02.cross(Tx07 - Tx02)
    print('J[{}][{}]={}'.format(0, 2, make_usable(str(sp.simplify(Jbuff[0][0])))))
    print('J[{}][{}]={}'.format(1, 2, make_usable(str(sp.simplify(Jbuff[1])))))
    print('J[{}][{}]={}'.format(2, 2, make_usable(str(sp.simplify(Jbuff[2])))))
    print('J[{}][{}]={}'.format(3, 2, make_usable(str(sp.simplify(To02[0])))))
    print('J[{}][{}]={}'.format(4, 2, make_usable(str(sp.simplify(To02[1])))))
    print('J[{}][{}]={}'.format(5, 2, make_usable(str(sp.simplify(To02[2])))))
    print('\n# q4')
    Jbuff = To03.cross(Tx07 - Tx03)
    print('J[{}][{}]={}'.format(0, 3, make_usable(str(sp.simplify(Jbuff[0])))))
    print('J[{}][{}]={}'.format(1, 3, make_usable(str(sp.simplify(Jbuff[1])))))
    print('J[{}][{}]={}'.format(2, 3, make_usable(str(sp.simplify(Jbuff[2])))))
    print('J[{}][{}]={}'.format(3, 3, make_usable(str(sp.simplify(To03[0])))))
    print('J[{}][{}]={}'.format(4, 3, make_usable(str(sp.simplify(To03[1])))))
    print('J[{}][{}]={}'.format(5, 3, make_usable(str(sp.simplify(To03[2])))))
    print('\n# q5')
    Jbuff = To04.cross(Tx07 - Tx04)
    print('J[{}][{}]={}'.format(0, 4, make_usable(str(sp.simplify(Jbuff[0])))))
    print('J[{}][{}]={}'.format(1, 4, make_usable(str(sp.simplify(Jbuff[1])))))
    print('J[{}][{}]={}'.format(2, 4, make_usable(str(sp.simplify(Jbuff[2])))))
    print('J[{}][{}]={}'.format(3, 4, make_usable(str(sp.simplify(To04[0])))))
    print('J[{}][{}]={}'.format(4, 4, make_usable(str(sp.simplify(To04[1])))))
    print('J[{}][{}]={}'.format(5, 4, make_usable(str(sp.simplify(To04[2])))))
    print('\n# q6')
    Jbuff = To05.cross(Tx07 - Tx05)
    print('J[{}][{}]={}'.format(0, 5, make_usable(str(sp.simplify(Jbuff[0])))))
    print('J[{}][{}]={}'.format(1, 5, make_usable(str(sp.simplify(Jbuff[1])))))
    print('J[{}][{}]={}'.format(2, 5, make_usable(str(sp.simplify(Jbuff[2])))))
    print('J[{}][{}]={}'.format(3, 5, make_usable(str(sp.simplify(To05[0])))))
    print('J[{}][{}]={}'.format(4, 5, make_usable(str(sp.simplify(To05[1])))))
    print('J[{}][{}]={}'.format(5, 5, make_usable(str(sp.simplify(To05[2])))))
    print('\n# q7')
    Jbuff = To06.cross(Tx07 - Tx06)
    print('J[{}][{}]={}'.format(0, 6, make_usable(str(sp.simplify(Jbuff[0])))))
    print('J[{}][{}]={}'.format(1, 6, make_usable(str(sp.simplify(Jbuff[1])))))
    print('J[{}][{}]={}'.format(2, 6, make_usable(str(sp.simplify(Jbuff[2])))))
    print('J[{}][{}]={}'.format(3, 6, make_usable(str(sp.simplify(To06[0])))))
    print('J[{}][{}]={}'.format(4, 6, make_usable(str(sp.simplify(To06[1])))))
    print('J[{}][{}]={}'.format(5, 6, make_usable(str(sp.simplify(To06[2])))))
    
    
    '''
    Tx = T * sp.Matrix([0,0,0,1])
    for ii in range(6):
        print ('#{}'.format(q[ii]))
        print ('J[{}][{}]={}'.format(0, ii, make_usable(str(sp.simplify(Tx[0].diff(q[ii]))))))
        print ('J[{}][{}]={}'.format(1, ii, make_usable(str(sp.simplify(Tx[1].diff(q[ii]))))))
        print ('J[{}][{}]={}'.format(2, ii, make_usable(str(sp.simplify(Tx[2].diff(q[ii]))))))
        print ('J[{}][{}]={}'.format(3, ii, make_usable(str(sp.simplify(To[ii][0])))))
        print ('J[{}][{}]={}'.format(4, ii, make_usable(str(sp.simplify(To[ii][1])))))
        print ('J[{}][{}]={}'.format(5, ii, make_usable(str(sp.simplify(To[ii][2])))))
        print ('\n\n')
    '''
calc_transform()

Matrix([[l1*sin(q0)*sin(q1) - l2*(-(sin(q0)*cos(q1)*cos(q2) + sin(q2)*cos(q0))*sin(q3) - sin(q0)*sin(q1)*cos(q3)) - l3*(-(((sin(q0)*cos(q1)*cos(q2) + sin(q2)*cos(q0))*cos(q3) - sin(q0)*sin(q1)*sin(q3))*cos(q4) + (-sin(q0)*sin(q2)*cos(q1) + cos(q0)*cos(q2))*sin(q4))*sin(q5) + (-(sin(q0)*cos(q1)*cos(q2) + sin(q2)*cos(q0))*sin(q3) - sin(q0)*sin(q1)*cos(q3))*cos(q5))], [-l1*sin(q1)*cos(q0) + l2*(-(-sin(q0)*sin(q2) + cos(q0)*cos(q1)*cos(q2))*sin(q3) - sin(q1)*cos(q0)*cos(q3)) + l3*(-(((-sin(q0)*sin(q2) + cos(q0)*cos(q1)*cos(q2))*cos(q3) - sin(q1)*sin(q3)*cos(q0))*cos(q4) + (-sin(q0)*cos(q2) - sin(q2)*cos(q0)*cos(q1))*sin(q4))*sin(q5) + (-(-sin(q0)*sin(q2) + cos(q0)*cos(q1)*cos(q2))*sin(q3) - sin(q1)*cos(q0)*cos(q3))*cos(q5))], [0]])
(3, 1)

# q1


KeyboardInterrupt: 

In [ ]:
import sympy as sp
 
def calc_transform():
    # set up our joint angle symbols (6th angle doesn't affect any kinematics)
    q = [sp.Symbol('q0'), sp.Symbol('q1'), sp.Symbol('q2'), sp.Symbol('q3'),
            sp.Symbol('q4'), sp.Symbol('q5')]
    # set up our arm segment length symbols
    l1 = sp.Symbol('l1')
    l3 = sp.Symbol('l3')
    l5 = sp.Symbol('l5')
 
    Torg0 = sp.Matrix([[sp.cos(q[0]), -sp.sin(q[0]), 0, 0,],
                       [sp.sin(q[0]), sp.cos(q[0]), 0, 0],
                       [0, 0, 1, 0],
                       [0, 0, 0, 1]])
 
    T01 = sp.Matrix([[1, 0, 0, 0],
                     [0, sp.cos(q[1]), -sp.sin(q[1]), l1*sp.cos(q[1])],
                     [0, sp.sin(q[1]), sp.cos(q[1]), l1*sp.sin(q[1])],
                     [0, 0, 0, 1]])
 
    T12 = sp.Matrix([[1, 0, 0, 0],
                     [0, sp.cos(q[2]), -sp.sin(q[2]), 0],
                     [0, sp.sin(q[2]), sp.cos(q[2]), 0],
                     [0, 0, 0, 1]])
 
    T23 = sp.Matrix([[sp.cos(q[3]), 0, sp.sin(q[3]), 0],
                     [0, 1, 0, l3],
                     [-sp.sin(q[3]), 0, sp.cos(q[3]), 0],
                     [0, 0, 0, 1]])
 
    T34 = sp.Matrix([[1, 0, 0, 0],
                     [0, sp.cos(q[4]), -sp.sin(q[4]), 0],
                     [0, sp.sin(q[4]), sp.cos(q[4]), 0],Alan Dershowitz
                     [0, 0, 0, 1]])
 
    T45 = sp.Matrix([[sp.cos(q[5]), 0, sp.sin(q[5]), 0],
                     [0, 1, 0, l5],
                     [-sp.sin(q[5]), 0, sp.cos(q[5]), 0],
                     [0, 0, 0, 1]])
 
    T = Torg0 * T01 * T12 * T23 * T34 * T45
 
    # position of the end-effector relative to joint axes 6 (right at the origin)
    x = sp.Matrix([0,0,0,1])
 
    Tx = T * x
 
    for ii in range(6):
        print (q[ii])
        print (sp.simplify(Tx[0].diff(q[ii])))
        print (sp.simplify(Tx[1].diff(q[ii])))
        print (sp.simplify(Tx[2].diff(q[ii])))
calc_transform()